// Generated by the spaces CLI. Do not edit by hand.

import { executeAction, executeActionStream } from "@hatch/sdk";

export type GetCronJobsRequest = Record<string, unknown>;

export type GetCronJobsResponse = {
  active: number;
  disabled: number;
  jobs: Array<{
  body_preview: string;
  cadence_group: string;
  enabled: boolean;
  file_path: string;
  id: string;
  mode: string;
  schedule_display: string;
  schedule_dom?: Array<number> | null;
  schedule_dow?: Array<string> | null;
  schedule_every?: string | null;
  schedule_kind: string;
  schedule_time?: string | null;
}>;
  total: number;
};

export class Space {
  static getCronJobs(request: GetCronJobsRequest): Promise<GetCronJobsResponse> {
    return executeAction<GetCronJobsResponse>("get_cron_jobs", request);
  }

  static getCronJobsStream(request: GetCronJobsRequest): AsyncIterable<GetCronJobsResponse> {
    return executeActionStream<GetCronJobsResponse>("get_cron_jobs", request);
  }

}
