// Generated by the spaces CLI. Do not edit by hand.

import { executeAction, executeActionStream } from "@hatch/sdk";

export type GetDaydreamStateRequest = Record<string, unknown>;

export type GetDaydreamStateResponse = {
  active_thread_names: Array<string>;
  article_seeds_content: string | null;
  instructions_content: string;
  instructions_version: string;
  iteration: number;
  last_report: string | null;
  last_run: string | null;
  questions_ray_would_love: Array<string>;
  seeded_articles: Array<string>;
  threads: Array<{
  content: string;
  filename: string;
  size_bytes: number;
  slug: string;
}>;
};

export class Space {
  static getDaydreamState(request: GetDaydreamStateRequest): Promise<GetDaydreamStateResponse> {
    return executeAction<GetDaydreamStateResponse>("get_daydream_state", request);
  }

  static getDaydreamStateStream(request: GetDaydreamStateRequest): AsyncIterable<GetDaydreamStateResponse> {
    return executeActionStream<GetDaydreamStateResponse>("get_daydream_state", request);
  }

}
