/* story-nav.js — auto-inject share buttons + prev/next article nav on all story pages */
(function() {
  'use strict';

  // Article order (newest first) — matches homepage grid order
  const articles = [
    "anthropic-80-percent-code-software-engineering-labor-math.html",
    "shield-ai-v-bat-170x-crash-rate-12-billion-valuation.html",
    "nasa-moon-base-clps-delivery-gap.html",
    "quantinuum-ipo-410x-revenue-quantum-computing.html",
    "pcsk9-embryo-base-editing-mosaicism-gap.html",
    "anthropic-965b-valuation-revenue-curve-ipo-pipeline.html",
    "microsoft-mai-data-provenance-contradiction-openai-breakup.html",
    "fusion-biggest-week-physics-validated-billions-raised.html",
    "daraxonrasib-ras-undruggable-pancreatic-cancer-standing-ovation.html",
    "great-american-ai-act-preemption-gap.html",
    "anthropic-pause-verification-game-theory.html",
    "nvidia-reference-humanoid-robot-brain-tax.html",
    "waymo-ojai-purpose-built-robotaxi-cost-math.html",
    "alphabet-85b-equity-ai-capex-exceeds-cash-flow.html",
    "magnetoelectric-microrobots-spinal-cord-regeneration-mice.html",
    "microsoft-ai-data-center-clean-energy-retreat.html",
    "apple-gemini-siri-billion-dollar-outsource.html",
    "uber-avride-16-crashes-safety-monitor-failure.html",
    "car-t-solid-tumors-asco-2026-three-programs.html",
    "direct-lithium-extraction-us-brine-race.html",
    "asr-sota-on-device-vs-cloud.html",
    "warming-acceleration-clean-air-paradox.html",
    "agentic-news-media-consumer-advocacy.html",
    "fbi-ai-fraud-first-count.html",
    "weekly-ai-roundup-june-1-2026.html",
    "hyundai-25000-atlas-robots-us-factories.html",
    "dell-ai-servers-surpass-pcs-51-billion-backlog.html",
    "nvidia-n1x-1000-tops-cuda-comes-to-laptops.html",
    "blue-origin-one-pad-three-programs-zero-backup.html",
    "anthropic-965b-valuation-revenue-curve.html",
    "robinhood-ai-agents-correlation-bomb.html",
    "gpu-utilization-five-percent-725-billion-ai-capex.html",
    "doe-weapons-plutonium-20-metric-tons-five-startups-zero-reactors.html",
    "ai-data-center-backlash-69-bans-grid-alert.html",
    "micron-trillion-14x-memory-shortage-ai-tax.html",
    "anthropic-xai-compute-rental.html",
    "pope-ai-encyclical-market-concentration.html",
    "press-credential-collapse-anyone-journalist.html",
    "spacex-starlink-pentagon-drone-pricing-monopoly-tax.html",
    "figure-f03-200-hours-250000-packages-zero-failures.html",
    "chi-bench-ai-agents-fail-healthcare-workflows.html",
    "weekly-ai-roundup-may-24-2026.html",
    "nextera-dominion-67b-merger-ai-power-play.html",
    "openai-erdos-unit-distance-ai-math-proof.html",
    "xenon-short-arc-perimeter-defense.html",
    "us-biomanufacturing-500m-capacity-gap.html",
    "megaconstellation-black-carbon-540x-accidental-geoengineering.html",
    "us-2-billion-quantum-grants-equity-stakes-nine-firms.html",
    "china-robotaxi-mass-production-three-architectures.html",
    "china-space-solar-beam-100m-orbit-gap.html",
    "stanchart-lower-value-human-capital.html",
    "google-io-2026-token-price-paradox-agent-lock-in.html",
    "tesla-fremont-robot-factory-production-gap.html",
    "google-190-billion-ai-capex-per-token-per-user-math.html",
    "googlebook-1000-dollar-laptop-38-million-students.html",
    "stellest-myopia-control-first-fda-spectacle-lens.html",
    "senolytics-zombie-cell-trials-myelin-risk.html",
    "samsung-strike-worst-memory-shortage-15-years.html",
    "chrome-gemini-nano-4gb-silent-install-carbon-cost.html",
    "photonic-computing-30-watts-billion-parameters.html",
    "ukraine-robot-only-position-capture-warfare-threshold.html",
    "fda-one-trial-standard-evidence-gamble.html",
    "apple-bci-protocol-fewer-than-100-users.html",
    "anthropic-mythos-one-cve-thousands-claim.html",
    "ai-wildfire-cameras-beat-911.html",
    "cowos-packaging-monopoly-crack.html",
    "pjm-data-center-electricity-bill-shock.html",
    "ai-ip-clean-room-rewrite.html",
    "weekly-ai-roundup-may-17-2026.html",
    "ukraine-25000-robots-ground-war-procurement-gap.html",
    "byd-gods-eye-data-war-autonomous-driving.html",
    "ai-code-bug-epidemic-half-github-security-flaws.html",
    "radiopharmaceutical-isotope-bottleneck-26b-market.html",
    "in-vivo-car-t-race-eliminate-factory.html",
    "robot-orders-auto-collapse-pharma-surge.html",
    "apoe2-neurons-resist-aging-dna-repair.html",
    "desalination-119m-xprize-water-gap.html",
    "quantum-error-correction-five-breakthroughs-may-2026.html",
    "cultivated-meat-pet-food-pivot-93-percent-funding-collapse.html",
    "perovskite-solar-12-records-none-shipped.html",
    "orbital-data-center-race-million-satellites.html",
    "data-center-29-million-gallons-georgia-drought.html",
    "ai-built-zero-day-exploit-first-confirmed-case.html",
    "orbital-house-of-cards-crash-clock-2-8-days.html",
    "ai-layoffs-productivity-paradox-q1-2026.html",
    "alphaevolve-self-improving-ai-substrate.html",
    "fusion-experience-rate-cost-myth.html",
    "robot-scientist-50000-solar-cell-experiments.html",
    "swift-telescope-30m-rescue-falling-from-orbit.html",
    "ai-self-replication-6-to-81-percent-safety-relaxed.html",
    "home-humanoid-20000-dollars-human-in-loop.html",
    "weekly-ai-roundup-may-11-2026.html",
    "first-systematic-review-ai-displacement-94-studies.html",
    "ai-drug-discovery-173-compounds-phase-iii-2026.html",
    "cosmic-ray-correlated-qubit-errors-underground-fix.html",
    "anthropic-nla-claude-hidden-evaluation-awareness.html",
    "crispr-cas12a2-cell-killing-paradigm-shift.html",
    "ai-weather-models-fail-extreme-events.html",
    "bci-convergence-five-implants-three-weeks.html",
    "prime-assembly-11kb-gene-replacement.html",
    "launch-failure-true-cost-67x-ratio.html",
    "solid-state-cooling-refrigerant-race.html",
    "caisi-five-labs-open-source-gap.html",
    "pentagon-classified-ai-any-lawful-purpose.html",
    "quantum-3000x-speedup-verification-gap.html",
    "glp1-muscle-loss-race-fix.html",
    "panthalassa-wave-ocean-ai-data-center.html",
    "unconscious-hippocampus-language-prediction.html",
    "boston-dynamics-atlas-625x-production-gap.html",
    "fervo-geothermal-ipo-fracking-clean-energy.html",
    "av-funding-concentration-three-companies-84-percent.html",
    "magnon-lifetime-100x-mini-quantum-computer.html",
    "nist-caisi-deepseek-v4-benchmark-gap.html",
    "mit-pencil-beam-bbb-imaging-25x-faster.html",
    "dac-opportunity-cost-renewables-nature-study.html",
    "california-av-regulations-ticket-trucks-paradox.html",
    "pentagon-dawg-55b-drone-industrial-base.html",
    "humanoid-robot-factory-race-cost-per-hour.html",
    "weekly-ai-roundup-may-4-2026.html",
    "nrc-part-57-microreactor-ai-data-center.html",
    "us-eastern-range-five-rockets-sixty-year-record.html",
    "mayo-clinic-redmod-pancreatic-cancer-ai.html",
    "china-ai-layoffs-illegal-global-comparison.html",
    "catl-4-minute-battery-grid-bottleneck.html",
    "ai-designed-ribosome-19-amino-acids.html",
    "cortec-bidirectional-bci-stroke-pong.html",
    "intellia-lonvoz-crispr-hae-one-dose-cure.html",
    "1x-neo-teleoperation-economics.html",
    "joby-nyc-evtol-throughput-ceiling.html",
    "pentagon-drone-budget-244x.html",
    "fda-real-time-clinical-trials-dead-time.html",
    "ai-self-automation-clone-yourself.html",
    "terrapower-natrium-construction-cost-reality.html",
    "xreal-ipo-smart-glasses-unit-economics.html",
    "stratos-dac-scaling-math.html",
    "cfs-pjm-fusion-grid-critical-path.html",
    "quantum-ecc-15bit-bitcoin-migration-gap.html",
    "solid-state-battery-robots-first.html",
    "navy-underwater-drone-pivot-orca-deep-thoughts.html",
    "closed-loop-human-neurotransmitter-optimization.html",
    "ai-agents-public-employee-transparency-foia.html",
    "anthropic-automated-alignment-agents-outperform-humans.html",
    "sony-ace-robot-beats-elite-table-tennis-nature.html",
    "cambridge-memristor-ai-energy-70-percent.html",
    "free-ai-tutor-15-dollar-calculation.html",
    "hiv-drug-reverses-biological-age-six-years.html",
    "tesla-cybercab-self-certifies-crash-rate-nine-times-human.html",
    "weekly-ai-roundup-april-27-2026.html",
    "printed-neuron-stimulates-real-brain-cells.html",
    "muon-catalyzed-fusion-room-temperature-energy-gap.html",
    "humanoid-robot-half-marathon-100-minute-improvement.html",
    "gpt55-hallucination-benchmark-incentive-paradox.html",
    "ai-fact-check-failure-billionaire-tax.html",
    "deezer-ai-music-75000-tracks-royalty-dilution.html",
    "catl-sodium-ion-battery-lithium-disruption.html",
    "microplastics-brain-heart-cancer-body-burden.html",
    "evtol-certification-race-unit-economics-gap.html",
    "ai-benchmark-saturation-measurement-crisis.html",
    "physical-intelligence-pi07-robot-generalization-data-gap.html",
    "tesla-cybercab-self-certification-regulatory-paradox.html",
    "quaise-superhot-geothermal-drilling-gap.html",
    "co2-blood-chemistry-population-shift.html",
    "in-vivo-crispr-attr-clinical-race.html",
    "fermionic-quantum-gates-error-correction-threshold.html",
    "bci-electrode-count-vs-safety-data.html",
    "helium-chokepoint-ai-chip-crisis.html",
    "kairos-hermes2-nuclear-construction-reality.html",
    "solid-state-battery-broken-promises-scorecard.html",
    "ai-data-center-water-disclosure-gap.html",
    "apple-hardware-ceo-ternus-mag7.html",
    "ai-coding-trust-gap.html",
    "china-ai-chip-procurement-gap.html",
    "tesla-robotaxi-announcement-reality-gap.html",
    "apple-hardware-ceo-smart-glasses-bet.html",
    "pjm-data-center-rate-shock-ratepayer-bill.html",
    "xai-colossus-memphis-pollution-cost.html",
    "apple-india-tariff-supply-chain-math.html",
    "oral-glp1-pill-era-foundayo-math.html",
    "eu-ai-act-compliance-cliff-august-deadline.html",
    "ai-chip-smuggling-enforcement-gap.html",
    "second-life-ev-batteries-grid-storage-math.html",
    "starship-v3-orbital-refueling-artemis-gap.html",
    "uk-smr-factory-nuclear-cost-gap.html",
    "tsmc-cowos-ai-packaging-bottleneck.html",
    "miniature-crispr-aav-delivery-breakthrough.html",
    "deepfake-fraud-detection-gap.html",
    "solid-state-battery-race.html",
    "autonomous-ew-drone-swarms.html",
    "lab-grown-cocoa-bioreactor-economics.html",
    "ftl1-memory-reversal-iron-aging-brain.html",
    "gene-therapy-deafness-cure-race.html",
    "ocean-alkalinity-first-verified-credits.html",
    "ai-layoffs-capex-trade.html",
    "pentagon-cca-drone-wingman-billion-dollar-bet.html",
    "pig-kidney-xenotransplant-gene-editing-race.html",
    "ai-generational-fumble-sentiment-crisis.html",
    "china-first-commercial-bci-regulatory-race.html",
    "molecular-farming-third-path-protein.html",
    "navy-submarine-3d-printing-industrial-base.html",
    "nine-ai-agents-community-identity-crisis.html",
    "interconnection-queue-fossil-backdoor.html",
    "stem-cell-frailty-63-meters-cost-conundrum.html",
    "autonomous-trucking-250k-miles-hos-economics.html",
    "compact-laser-accelerator-8-hour-fel.html",
    "india-pfbr-fast-breeder-thorium-bridge.html",
    "rna-editing-paradigm-shift.html",
    "spacex-ipo-1-75-trillion-valuation-math.html",
    "cortec-therapeutic-bci-stroke-market.html",
    "photonic-interconnect-ai-copper-wall.html",
    "solar-geoengineering-private-capital-governance-gap.html",
    "agrifoodtech-deeptech-valley-of-death.html",
    "fervo-geothermal-bankability-inflection.html",
    "japan-shield-autonomous-drone-defense.html",
    "mythos-preview-ai-zero-day-cybersecurity.html",
    "rapamycin-longevity-trial-human-evidence.html",
    "apartment-supply-cliff-housing-gap-math.html",
    "byd-price-war-export-profitability-crisis.html",
    "gene-drive-mosquitoes-malaria-tanzania-test.html",
    "humanoid-robots-10000-units-factory-economics.html",
    "ai-jevons-paradox-630-billion-capex.html",
    "apple-watch-hypertension-41-percent.html",
    "eu-carbon-border-tax-cbam-who-pays.html",
    "fusion-10-billion-zero-kilowatt-hours.html",
    "ai-entry-level-paradox.html",
    "k12-curriculum-ai-age-april-2026.html",
    "nhs-galleri-stage-shift-paradox.html",
    "pentagon-ai-vendor-concentration-paradox.html",
    "ai-defense-midterms-fight-fire-with-fire.html",
    "ai-propaganda-machine-we-accidentally-built.html",
    "deep-sea-mining-ccz-resource-race.html",
    "democracy-ai-age-governance-failure-modes.html",
    "eipp-concentration-risk-analysis.html",
    "military-3d-printed-construction-scorecard.html",
    "open-source-gatekeepers-quality-suspicious.html",
    "battery-storage-gas-crossover.html",
    "claude-code-dmca-copyright-paradox.html",
    "claude-code-leaked-source-clean-room-rewrites.html",
    "convergent-architecture-persistent-ai-agents.html",
    "ev-used-market-lease-wave.html",
    "glp1-mortality-coverage.html",
    "liberation-day-manufacturing-scorecard.html",
    "robotaxi-correlated-failure-risk.html",
    "starship-90-million-launch-cost.html",
    "artemis-ii-cost-per-astronaut-hour.html",
    "carbon-removal-delivery-gap.html",
    "humanoid-robot-16000-units-deployment-gap.html",
    "swe-bench-reality-gap.html",
    "sweden-tablet-reversal-reading-scores.html",
    "glp1-protein-apocalypse-precision-fermentation.html",
    "junior-developer-pipeline-collapse.html",
    "offshore-wind-self-inflicted-energy-crisis.html",
    "satellite-methane-emissions-accountability.html",
    "sodium-ion-battery-lithium-free-ev-era.html",
    "synchron-endovascular-bci-wins-regulatory-race.html",
    "ai-inference-deflation-curve.html",
    "fda-plausible-mechanism-crispr-one-patient.html",
    "openai-sora-gpu-triage.html",
    "ai-week-march-29-2026.html",
    "biocomputing-neurons-for-sale.html",
    "perovskite-efficiency-gap.html",
    "bci-typing-speed-commercial-era.html",
    "beam-302-base-editing-gene-correction.html",
    "glp-1-oral-pill-pricing-revolution.html",
    "rare-earth-supply-cliff-april-2026.html",
    "cloud-infrastructure-first-kinetic-attack.html",
    "hardware-cost-advantage-bom-mva-apple-amazon-samsung.html",
    "wifi-jammer-detection-ai-neighborhood-security.html",
    "ai-medical-consulting-transformation.html",
    "ai-confidence-calibration-theatre.html",
    "matrix-org-ai-decision-bottleneck.html",
    "nuclear-microreactors-operation-windlord.html",
    "performance-marketing-conversion-signal-delay.html",
    "pentagon-autonomy-budget-13-billion.html",
    "pdf-to-markdown-conversion-token-formatting-benchmark.html",
    "psilocybin-phase-3-treatment-resistant-depression.html",
    "personalized-mrna-cancer-vaccine-five-year-data.html",
    "drone-delivery-hits-scale.html",
    "autonomous-ships-beat-cars.html",
    "jupitercore-diy-ai-agent-local-inference.html",
    "ev-subsidy-natural-experiment.html",
    "humanoid-robot-valuation-gap.html",
    "nhtsa-rewriting-rules-driverless-cars.html",
    "dac-delivery-gap-2-million-tonnes-sold-1186-delivered.html",
    "computational-photography-isp-diffusion-fabrication.html",
    "pjm-rate-shock-data-centers-rewriting-electricity-bills.html",
    "china-thousand-sails-vs-starlink-deployment-gap.html",
    "private-fusion-outspends-iter-per-milestone.html",
    "anduril-arsenal-1-autonomous-weapons-factory.html",
    "ai-designed-living-genomes-evo2-phage.html",
    "ai-political-coalition-regulation-nuclear-scenario.html",
    "california-backflow-testing-300-million-racket.html",
    "new-yorker-claude-anthropic-response.html",
    "california-common-core-math-seven-weeks-rounding.html",
    "nevi-ev-charging-scorecard.html",
    "solid-state-battery-scorecard-2026.html",
    "dac-scorecard-carbon-removal-cost.html",
    "braingate-qwerty-bci-typing-speed.html",
    "bmw-humanoid-robot-factory-scorecard.html",
    "laziness-biochemistry-motivation-pill.html",
    "casgevy-two-year-scorecard.html",
    "starlink-direct-to-cell-death-of-dead-zones.html",
    "chips-act-reshoring-scorecard.html",
    "pig-kidney-xenotransplant-scorecard.html",
    "ai-makes-students-worse.html",
    "ai-weather-forecasting-replaces-supercomputers.html",
    "california-325-billion-budget-outcomes.html",
    "beyond-engagement-five-optimization-functions.html",
    "ai-risk-brave-new-world-not-terminator.html",
    "agent-skill-supply-chain-attack-clawhavoc.html",
    "ai-automotive-design-gigacasting-generative-revolution.html",
    "ai-designed-watches-materials-revolution.html",
    "ai-generated-prior-art-patent-troll-weapon.html",
    "ai-drug-discovery-first-clinical-proof.html",
    "computational-pre-purchase-eyewear-fitting.html",
    "linkedin-thought-leadership-ai-authenticity-crisis.html",
    "long-short-strategies-quant-democratization.html",
    "personal-finance-democratization-next-unlock.html",
    "ai-allergy-management-personalized-prediction.html",
    "ecommerce-funnel-collapse.html",
    "dlss5-art-direction-override.html",
    "ai-latency-200ms-conversational-threshold.html",
    "model-collapse-ai-eating-itself.html",
    "hbm-memory-bottleneck-ai-cannibalizing-consumer.html",
    "ukraine-drone-ai-data-marketplace.html",
    "cultivated-meat-survivors.html",
    "one-shot-cholesterol-cure.html",
    "bloom-two-sigma-ai-tutor.html",
    "iron-air-battery-ai-grid.html",
    "poe-alarm-listener.html",
    "neom-500-billion-mirage.html",
    "humanoid-robots-demo-to-deployment.html",
    "glp1-accidental-longevity-drug.html",
    "ai-water-crisis.html",
    "covid-smell-loss-poop-detector.html",
    "ai-scheduler-os-design.html",
    "algorithmic-war-iran-ai-targeting.html",
    "humanoid-deployment-gap.html",
    "waymo-million-rides-five-billion-hole.html",
    "ai-copyright-our-own-reckoning.html",
    "ai-personalized-education-vs-standardized.html",
    "wire-rewrite-two-tier-copyright.html",
    "ai-task-factory-recursion.html",
    "commission-capture.html",
    "ai-transformation-80k-company.html",
    "two-wave-displacement.html",
    "compounding-crisis-oil-ai.html",
    "monetary-policy-blind-spot.html",
    "solid-state-battery-verification-year.html",
    "reprogramming-race-first-human.html",
    "great-decoupling-permanent.html",
    "china-robot-takeover.html",
    "nuclear-ai-datacenter-gap.html",
    "evtol-air-taxi-reckoning.html",
    "small-launch-graveyard.html",
    "space-debris-cleanup-market.html",
    "chip-sanctions-scorecard.html",
    "vertical-farming-financial-reckoning.html",
    "marine-cloud-brightening.html",
    "noninvasive-bci-signal-problem.html",
    "housing-deficit-technology-gap.html",
    "gene-therapy-pricing-crisis.html",
    "anti-aging-drug-scorecard.html",
    "shadow-agent-proliferation.html",
    "geothermal-fracking-revolution.html",
    "neuromorphic-chip-energy-gap.html",
    "post-quantum-crypto-migration.html",
    "deploy-maximum-protect-zero.html",
    "15-minute-city-backlash-data.html",
    "space-station-customer-problem.html",
    "fpv-drone-economics.html",
    "humanoid-robot-price-war.html",
    "carbon-credit-market-split.html",
    "degradation-pipeline.html",
    "precision-fermentation-winning.html",
    "bci-patient-outcomes.html",
    "ethics-premium-consumer-revolt.html",
    "ethics-premium-displacement-theater.html",
    "trades-as-refuge-trap.html",
    "retraining-industry-failure.html",
    "delegation-flip.html",
    "doge-displacement-case-study.html",
    "ai-productivity-perception-gap.html",
    "klarna-invisible-layoffs.html",
    "synbio-economic-reckoning.html",
    "glp1-longevity-drug.html",
    "autonomous-trucking-graveyard.html",
    "fusion-vs-solar-economics.html",
    "smart-city-graveyard.html",
    "drone-warfare-economics.html",
    "direct-air-capture-cost.html",
    "crispr-access-gap.html",
    "bci-bandwidth-race.html",
    "quantum-error-correction.html",
    "cultivated-meat-price.html",
    "humanoid-robot-cost.html",
    "battery-storage-revolution.html",
    "longevity-escape-velocity.html",
    "spacex-launch-cost.html",
    "waymo-deaths-per-mile.html"
  ];
  var currentIdx = -1;
  for (var i = 0; i < articles.length; i++) {
    if (articles[i].slug === currentSlug) { currentIdx = i; break; }
  }

  // --- Share buttons ---
  var existingShare = document.querySelector('.share-bar');
  if (!existingShare) {
    var title = document.querySelector('.story-title');
    var meta = document.querySelector('.story-byline') || document.querySelector('.story-meta');
    if (title && meta) {
      var url = encodeURIComponent(window.location.href);
      var text = encodeURIComponent(title.textContent.trim());
      var shareHtml = '<div class="share-bar">' +
        '<span class="share-label">Share</span>' +
        '<a class="share-btn" href="https://twitter.com/intent/tweet?url=' + url + '&text=' + text + '" target="_blank" rel="noopener" title="Share on 𝕏">𝕏</a>' +
        '<a class="share-btn" href="https://www.linkedin.com/sharing/share-offsite/?url=' + url + '" target="_blank" rel="noopener" title="Share on LinkedIn">in</a>' +
        '<a class="share-btn" href="https://reddit.com/submit?url=' + url + '&title=' + text + '" target="_blank" rel="noopener" title="Share on Reddit">R</a>' +
        '<a class="share-btn" href="https://news.ycombinator.com/submitlink?u=' + url + '&t=' + text + '" target="_blank" rel="noopener" title="Share on Hacker News">Y</a>' +
        '<button class="share-btn share-copy" onclick="navigator.clipboard.writeText(window.location.href).then(function(){this.textContent=\'✓\';var b=this;setTimeout(function(){b.textContent=\'🔗\'},1500)}.bind(this))" title="Copy link">🔗</button>' +
        '</div>';
      meta.insertAdjacentHTML('afterend', shareHtml);
    }
  }

  // --- Prev/Next navigation ---
  if (currentIdx === -1) return;

  var newer = currentIdx > 0 ? articles[currentIdx - 1] : null;
  var older = currentIdx < articles.length - 1 ? articles[currentIdx + 1] : null;

  var navHtml = '<nav class="article-nav">';
  if (older) {
    navHtml += '<a href="' + older.slug + '.html" class="nav-link nav-older">' +
      '<span class="nav-dir">← Older</span>' +
      '<span class="nav-title">' + older.title + '</span></a>';
  } else {
    navHtml += '<span class="nav-link nav-placeholder"></span>';
  }
  if (newer) {
    navHtml += '<a href="' + newer.slug + '.html" class="nav-link nav-newer">' +
      '<span class="nav-dir">Newer →</span>' +
      '<span class="nav-title">' + newer.title + '</span></a>';
  } else {
    navHtml += '<span class="nav-link nav-placeholder"></span>';
  }
  navHtml += '</nav>';

  // Insert before the closing </article> or at the end of the story page
  var article = document.querySelector('.story-page');
  if (article) {
    article.insertAdjacentHTML('beforeend', navHtml);
  }
})();
