/* story-nav.js — auto-inject share buttons + prev/next article nav on all story pages */
(function() {
  'use strict';

  // Article order (newest first) — matches homepage grid order
  var articles = [
    { slug: 'crispr-cas12a2-cell-killing-paradigm-shift', title: 'A New CRISPR Protein Destroyed Over 90% of Virus-Infected Cells and Left Every Healthy One Untouched \u2014 Live in the Future' },
    { slug: 'ai-weather-models-fail-extreme-events', title: 'AI Weather Models Beat Forecasters 364 Days a Year. On the Day That Kills People, They Choke. \u2014 Live in the Future' },
    { slug: 'bci-convergence-five-implants-three-weeks', title: 'Fifty People on Earth Have Brain Implants. Five Companies Just Expanded the List of Reasons to Get One by 10x. \u2014 Live in the Future' },
    { slug: 'prime-assembly-11kb-gene-replacement', title: 'Two Labs Just Cracked the Size Limit on Gene Editing. The Old Ceiling Was 800 Base Pairs. The New One Is 11,000. \u2014 Live in the Future' },
    { slug: 'launch-failure-true-cost-67x-ratio', title: 'A $30 Million Satellite Died. The Bill Was $2 Billion. \u2014 Live in the Future' },
    { slug: 'solid-state-cooling-refrigerant-race', title: 'Your Refrigerator Works the Same Way It Did in 1930. Three Labs Are Racing to Fix That Before 2036. \u2014 Live in the Future' },
    { slug: 'caisi-five-labs-open-source-gap', title: 'The Government Will Test Every Major AI Model Before Release. The One With 1 Billion Downloads Isn\u2019t on the List. \u2014 Live in the Future' },
    { slug: 'pentagon-classified-ai-any-lawful-purpose', title: 'Anthropic Was the Only AI on the Pentagon\u2019s Classified Networks. It Lost a $200 Million Contract for Refusing One Clause. Eight Companies Signed It. \u2014 Live in the Future' },
    { slug: 'quantum-3000x-speedup-verification-gap', title: 'A Quantum Computer Finished a Materials Simulation in Two Minutes. The Classical Machine Needed 100 Hours. Nobody Can Prove Who Got the Right Answer. \u2014 Live in the Future' },
    { slug: 'glp1-muscle-loss-race-fix', title: 'Semaglutide Dissolves 23 Pounds in 26 Weeks. Eight of Those Pounds Are Muscle. Four Companies Are Racing to Fix the Ratio. \u2014 Live in the Future' },
    { slug: 'panthalassa-wave-ocean-ai-data-center', title: 'Panthalassa Claims It Can Run AI on Ocean Waves for $0.02/kWh. The Wave Energy Industry Average Is $0.30. \u2014 Live in the Future' },
    { slug: 'unconscious-hippocampus-language-prediction', title: 'Seven Patients Were Under General Anesthesia. Their Brains Were Predicting the Next Word of a Podcast. \u2014 Live in the Future' },
    { slug: 'boston-dynamics-atlas-625x-production-gap', title: 'Boston Dynamics Makes 4 Robots a Month. Hyundai Wants 30,000 a Year. The C-Suite Left. \u2014 Live in the Future' },
    { slug: 'fervo-geothermal-ipo-fracking-clean-energy', title: 'Fervo Energy Wants $6.5 Billion to Turn Fracking Rigs Into Clean Power Plants. Its Contracted Revenue Already Exceeds That. \u2014 Live in the Future' },
    { slug: 'av-funding-concentration-three-companies-84-percent', title: 'Three Companies Got 84% of $21.4 Billion in AV Funding. Each Waymo Ride Now Costs Investors More Than a First-Class Plane Ticket. \u2014 Live in the Future' },
    { slug: 'magnon-lifetime-100x-mini-quantum-computer', title: 'A Magnetization Wave Survived 18 Microseconds Inside a Crystal. The Old Record Was 200 Nanoseconds. The Bottleneck Was Never Physics. \u2014 Live in the Future' },
    { slug: 'dac-opportunity-cost-renewables-nature-study', title: 'The U.S. Spent $3.5 Billion on Machines That Suck Carbon From the Air. A Nature Study Says Solar Panels Remove 10 Times More Carbon per Dollar. \u2014 Live in the Future' },
    { slug: 'mit-pencil-beam-bbb-imaging-25x-faster', title: 'An MIT Grad Student Cranked a Laser to Near-Destruction. The Chaos Organized Itself Into a Beam That Images the Blood-Brain Barrier 25 Times Faster. \u2014 Live in the Future' },
    { slug: 'california-av-regulations-ticket-trucks-paradox', title: 'California Wrote 100 Pages of Rules for Ticketing Robots. The Same Document Lets 80,000-Pound Trucks Drive Themselves. \u2014 Live in the Future' },
    { slug: 'weekly-ai-roundup-may-4-2026', title: 'The Week Four Companies Bet $725 Billion on a Market That Doesn\u2019t Exist Yet \u2014 Live in the Future' },
    { slug: 'humanoid-robot-factory-race-cost-per-hour', title: 'Three Companies Opened Humanoid Robot Factories in 120 Days. At $1.48 Per Hour, the Math Against Human Workers Was Already Done. \u2014 Live in the Future' },
    { slug: 'nist-caisi-deepseek-v4-benchmark-gap', title: 'DeepSeek Says It\u0027s 2 Months Behind GPT-5. NIST Says 8. The Difference Is Which Tests You Run. \u2014 Live in the Future' },
    { slug: 'nrc-part-57-microreactor-ai-data-center', title: 'The NRC Just Proposed a New Way to License Nuclear Reactors in 18 Months. The Old Way Took a Decade. Here\u0027s What Changed. \u2014 Live in the Future' },
    { slug: 'pentagon-dawg-55b-drone-industrial-base', title: 'The Pentagon Requested a 24,070% Increase in Drone Spending. US Factories Build Fewer Drones in a Year Than DJI Ships in Three Months. \u2014 Live in the Future' },
    { slug: 'us-eastern-range-five-rockets-sixty-year-record', title: 'Five Different Rockets Launched From the Same Spaceport in April. That Hadn\u0027t Happened in 60 Years. Here\u0027s What Each One Cost Per Kilogram. \u2014 Live in the Future' },
    { slug: 'mayo-clinic-redmod-pancreatic-cancer-ai', title: 'An AI Caught 73% of Invisible Pancreatic Cancers 475 Days Before Doctors Could. Running It on Every CT in America Would Cost $10 Per Scan. \u2014 Live in the Future' },
    { slug: 'china-ai-layoffs-illegal-global-comparison', title: 'A Chinese Court Says You Can\u0027t Fire Someone Because AI Took Their Job. In America, 160 Companies Filed AI Layoffs and Zero Called Them That. — Live in the Future' },
    { slug: 'catl-4-minute-battery-grid-bottleneck', title: 'CATL\'s New Battery Charges to 80% in Under 4 Minutes. The Grid Can Deliver That Power to Almost None of the World\'s Chargers. — Live in the Future' },
    { slug: 'ai-designed-ribosome-19-amino-acids', title: 'All Life Uses 20 Amino Acids. These Bacteria Run Their Most Ancient Machine on 19. — Live in the Future' },
    { slug: 'cortec-bidirectional-bci-stroke-pong', title: 'A Brain Implant Healed His Stroke. Then He Used It to Play Pong. No One Has Done Both Before. — Live in the Future' },
    { slug: 'intellia-lonvoz-crispr-hae-one-dose-cure', title: '62% of Patients Were Completely Cured by a Single IV Infusion. Current Treatment Costs $500,000 a Year. — Live in the Future' },
    { slug: '1x-neo-teleoperation-economics', title: '1X Sold 10,000 Robots in 5 Days. Each One Needs a Human Hiding Inside It. — Live in the Future' },
    { slug: 'joby-nyc-evtol-throughput-ceiling', title: 'Joby Flew JFK to Manhattan in 7 Minutes. 3 Heliports Can\'t Justify an $8.6 Billion Valuation. — Live in the Future' },
    { slug: 'pentagon-drone-budget-244x', title: 'The Pentagon Spent $225 Million on Drones Last Year. Now It Wants $55 Billion. Here\'s the Math That Forced the Pivot. — Live in the Future' },
    { slug: 'fda-real-time-clinical-trials-dead-time', title: 'The FDA Hasn\'t Changed How It Runs Clinical Trials in 60 Years. That Ended Monday. — Live in the Future' },
    { slug: 'ai-self-automation-clone-yourself', title: 'Try to Automate Your Entire Job. What\'s Left Is Why You\'re Valuable. | Live in the Future' },
    { slug: 'terrapower-natrium-construction-cost-reality', title: 'Bill Gates\' Nuclear Reactor Just Broke Ground. At $11,594 Per Kilowatt, Here\'s What \'Affordable\' Actually Means. — Live in the Future' },
    { slug: 'xreal-ipo-smart-glasses-unit-economics', title: 'The First Smart Glasses Company to Publish Audited Financials Ships 130,000 Units a Year. Meta Ships 7 Million. — Live in the Future' },
    { slug: 'stratos-dac-scaling-math', title: 'STRATOS Will Remove 500,000 Tons of CO2 Per Year. The Planet Emits 40 Billion. Here\'s the Math Nobody Wants to Do. — Live in the Future' },
    { slug: 'cfs-pjm-fusion-grid-critical-path', title: 'A Fusion Company Just Applied to Join America\'s Largest Power Grid. Here Are the 7 Things That Must Go Right. — Live in the Future' },
    { slug: 'quantum-ecc-15bit-bitcoin-migration-gap', title: 'A Quantum Computer Just Cracked a 15-Bit Key. Bitcoin Uses 256. The Math Between Them Is Changing Faster Than Anyone Expected. — Live in the Future' },
    { slug: 'solid-state-battery-robots-first', title: 'Solid-State Batteries Arrive in 2027. Robots Will Get Them First. Here\'s the $800 Reason Why. — Live in the Future' },
    { slug: 'navy-underwater-drone-pivot-orca-deep-thoughts', title: 'The Navy Spent $489 Million on Two Underwater Drones. Now DARPA Wants to Build Dozens for the Same Price. — Live in the Future' },
    { slug: 'closed-loop-human-neurotransmitter-optimization', title: 'The Closed-Loop Human Is 7 Years Away. Here Is What Already Works. — Live in the Future' },
    { slug: 'ai-agents-public-employee-transparency-foia', title: 'Every Public Employee in America Is Already Legally Observable. AI Agents Could Actually Do It. — Live in the Future' },
    { slug: 'anthropic-automated-alignment-agents-outperform-humans', title: 'The First AI System to Outperform Its Own Creators at Keeping AI Safe Cost $22 an Hour. — Live in the Future' },
    { slug: 'sony-ace-robot-beats-elite-table-tennis-nature', title: 'Sony\'s Robot Beat Elite Table Tennis Players. The 20-Millisecond Window That Made It Possible. — Live in the Future' },
    { slug: 'cambridge-memristor-ai-energy-70-percent', title: 'Cambridge Built a Brain-Inspired Chip That Uses a Million Times Less Current. AI\'s Energy Crisis Has a New Rival. — Live in the Future' },
    { slug: 'free-ai-tutor-15-dollar-calculation', title: 'A Free AI Tutor for Every Student Would Cost $8 Per Year. Nobody Is Building It. — Live in the Future' },
    { slug: 'hiv-drug-reverses-biological-age-six-years', title: 'An FDA-Approved Drug Cut Biological Age by 22% in 12 Weeks. It Wasn\'t Designed to Do That. — Live in the Future' },
    { slug: 'tesla-cybercab-self-certifies-crash-rate-nine-times-human', title: 'Tesla\'s Robotaxi Crashes 9x More Often Than a Human Driver. It Just Passed Every Federal Safety Standard. — Live in the Future' },
    { slug: 'weekly-ai-roundup-april-27-2026', title: 'The Week Three Frontier Models Dropped at Once — Live in the Future' },
    { slug: 'printed-neuron-stimulates-real-brain-cells', title: 'Brain-Computer Interfaces Can Read Your Neurons. This Printed Circuit Writes to Them. — Live in the Future' },
    { slug: 'muon-catalyzed-fusion-room-temperature-energy-gap', title: 'Room-Temperature Fusion Exists. It Returns 53 Cents on Every Dollar. — Live in the Future' },
    { slug: 'humanoid-robot-half-marathon-100-minute-improvement', title: 'In One Year, Humanoid Robots Improved Their Half-Marathon Time by 68%. Humans Needed a Century to Improve 14%. — Live in the Future' },
    { slug: 'gpt55-hallucination-benchmark-incentive-paradox', title: 'GPT-5.5 Tops Every AI Benchmark. It Also Hallucinates More Than Any Competitor. A Nature Paper Explains Why. — Live in the Future' },
    { slug: 'ai-fact-check-failure-billionaire-tax', title: 'I Fact-Checked a Billionaire’s Tax Tweet. I Was Wrong About Almost Everything. — Live in the Future' },
    { slug: 'deezer-ai-music-75000-tracks-royalty-dilution', title: '75,000 AI Songs Hit Deezer Every Day. Only One Streaming Platform Will Tell You Which Ones Are Real. — Live in the Future' },
    { slug: 'catl-sodium-ion-battery-lithium-disruption', title: 'CATL Spent $1.45 Billion to Build a Battery Without Lithium. Here Is What 70,000 Tonnes of Demand Destruction Looks Like. — Live in the Future' },
    { slug: 'microplastics-brain-heart-cancer-body-burden', title: 'Three Organs, Three Studies, One Material. The Evidence on Microplastics Is No Longer Preliminary. — Live in the Future' },
    { slug: 'evtol-certification-race-unit-economics-gap', title: 'China Sold a $41 Air Taxi Ticket This Month. America\'s Leading eVTOL Has Been in Certification for Nine Years.' },
    { slug: 'ai-benchmark-saturation-measurement-crisis', title: 'Nearly Half of AI\'s 60 Most-Cited Benchmarks Can No Longer Tell Models Apart. The Safety Tests Haven\'t Been Written.' },
    { slug: 'physical-intelligence-pi07-robot-generalization-data-gap', title: 'Physical Intelligence Trained Its Robot on 2 Air Fryer Episodes. It Cooked a Sweet Potato. The Valuation: $11 Billion.' },
    { slug: 'tesla-cybercab-self-certification-regulatory-paradox', title: 'The Safest Autonomous Fleet Is Capped at 2,500 Cars. The Least Safe One Has No Limit.' },
    { slug: 'quaise-superhot-geothermal-drilling-gap', title: 'Quaise Has Drilled 100 Meters with Millimeter Waves. It Needs 5,000. That 50× Gap Is the Biggest Bet in Clean Energy.' },
    { slug: 'co2-blood-chemistry-population-shift', title: '425 ppm Outside, 1,200 ppm in Your Office. A 21-Year Blood Study Shows the Body Keeps Score. — Live in the Future' },
    { slug: 'in-vivo-crispr-attr-clinical-race', title: 'A Single Injection Silenced a Disease Gene for 72 Weeks. The Cost of Not Doing It: $450,000 a Year.' },
    { slug: 'fermionic-quantum-gates-error-correction-threshold', title: 'Two Labs Built the Same Quantum Gate 25 Years After It Was Proposed. One Runs 17,000 at Once.' },
    { slug: 'bci-electrode-count-vs-safety-data', title: 'Neuralink Has 1,024 Electrodes and 21 Patients. Synchron Has 16 Electrodes and a Peer-Reviewed Safety Record. The Math Isn\'t What You Think.' },
    { slug: 'helium-chokepoint-ai-chip-crisis', title: 'Every Nvidia GPU Needs a Noble Gas Nobody Talks About. Qatar Just Stopped Shipping It.' },
    { slug: 'kairos-hermes2-nuclear-construction-reality', title: 'Google Needs 500 Megawatts of Nuclear Power by 2035. America Has Never Built a Reactor On Time.' },
    { slug: 'solid-state-battery-broken-promises-scorecard', title: '8 Companies Promised Solid-State Batteries by 2025. Zero Delivered. Now They\'re Promising 2027.' },
    { slug: 'ai-data-center-water-disclosure-gap', title: 'Every AI Company Reports Its Water Use. None of Them Report the Number That Matters.' },
    { slug: 'apple-hardware-ceo-ternus-mag7', title: 'Apple\'s New CEO Ran Every Product It Ships. Now He Inherits a Glasses War.' },
    { slug: 'ai-coding-trust-gap', title: '51% of Code on GitHub Is Now AI-Generated. The Developers Who Write It Trust It Less Than Ever.' },
    { slug: 'china-ai-chip-procurement-gap', title: 'Chinese Universities Ordered \'Domestic\' AI Chips. The Specs Only Match Nvidia\'s H200.' },
    { slug: 'tesla-robotaxi-announcement-reality-gap', title: '35 Cars, 15 Crashes, and 178× Earnings: The Math Behind Tesla\'s Robotaxi Announcements' },
    { slug: 'apple-hardware-ceo-smart-glasses-bet', title: 'Seven Million Smart Glasses Sold Last Year. None Were Apple\'s. John Ternus Plans to Change That.' },
    { slug: 'pjm-data-center-rate-shock-ratepayer-bill', title: 'PJM\'s Electricity Prices Jumped 1,038% in Three Years. Data Centers Caused 63% of It. Ratepayers Got 100% of the Bill.' },
    { slug: 'xai-colossus-memphis-pollution-cost', title: 'xAI Ran 35 Unpermitted Gas Turbines to Train Grok. A Harvard Study Says the Health Costs Are $30 Million a Year.' },
    { slug: 'apple-india-tariff-supply-chain-math', title: 'Apple Has Spent $3.3 Billion Absorbing Tariffs. Its $2.4 Billion Bet on India Is Designed to End the Bleeding.' },
    { slug: 'oral-glp1-pill-era-foundayo-math', title: 'Eli Lilly Built a $1.5 Billion Stockpile of Weight-Loss Pills. The Math Shows Why.' },
    { slug: 'eu-ai-act-compliance-cliff-august-deadline', title: '78% of Enterprises Aren\'t Ready for the EU AI Act. In 107 Days, the Fines Start at 7% of Global Revenue.' },
    { slug: 'ai-chip-smuggling-enforcement-gap', title: 'The U.S. Charged a Supermicro Co-Founder With Smuggling $2.5 Billion in AI Chips to China. The Black Market Premium Says He Wasn\'t Alone.' },
    { slug: 'second-life-ev-batteries-grid-storage-math', title: 'Rivian and Tesla\'s Co-Founder Are Turning Dead EV Batteries Into Grid Storage. The Math Says They Might Not Need New Ones. — Live in the Future' },
    { slug: 'starship-v3-orbital-refueling-artemis-gap', title: 'SpaceX Just Test-Fired Starship V3. It Still Needs 14 Refueling Flights Nobody Has Ever Tried. — Live in the Future' },
    { slug: 'apple-gemini-siri-billion-dollar-outsource', title: 'Apple Spent $34.5 Billion on R&D Last Year. It Still Had to Pay Google $1 Billion for AI. — Live in the Future' },
    { slug: 'uk-smr-factory-nuclear-cost-gap', title: 'Rolls-Royce Says It Can Build a Nuclear Reactor for £2 Billion. Hinkley Point C Costs £10.9 Billion Per Gigawatt. The Math Demands Scrutiny.' },
    { slug: 'tsmc-cowos-ai-packaging-bottleneck', title: 'TSMC Makes 3.65 Million AI Chip Modules a Year. The Industry Needs 5 Million. The Bottleneck Isn\'t Transistors.' },
    { slug: 'miniature-crispr-aav-delivery-breakthrough', title: 'A CRISPR Editor One-Third the Size of Cas9 Just Hit 90% Efficiency. The Delivery Bottleneck May Be Over.' },
    { slug: 'deepfake-fraud-detection-gap', title: 'It Costs $50 to Clone a CEO\'s Voice. The Industry Spent Billions on Detection. Detection Is Losing.' },
    { slug: 'solid-state-battery-race', title: '7 Companies Say Their Solid-State Batteries Ship by 2028. The World\'s Largest Battery Maker Says They Won\'t.' },
    { slug: 'autonomous-ew-drone-swarms', title: 'The Navy Has 160 Electronic Warfare Jets and No Replacement. L3Harris Just Showed Them One.' },
    { slug: 'lab-grown-cocoa-bioreactor-economics', title: 'Cocoa Hit $11,530 a Ton. Now Two Startups Are Growing It From Single Beans in Bioreactors.' },
    { slug: 'ftl1-memory-reversal-iron-aging-brain', title: 'One Protein Drove Memory Loss in Aged Mice. Removing It Brought Their Memories Back.' },
    { slug: 'gene-therapy-deafness-cure-race', title: '12 Children Were Born Deaf. 11 Can Hear Now. Five Teams Are Racing to Sell the Cure.' },
    { slug: 'ocean-alkalinity-first-verified-credits', title: '626 Tons of CO₂ Removed by Ocean Antacid. The Measurement Bill Was Higher Than the Chemistry.' },
    { slug: 'ai-layoffs-capex-trade', title: '150,000 Tech Workers Were Laid Off to Buy GPUs. 55% of Their Employers Already Regret It.' },
    { slug: 'pentagon-cca-drone-wingman-billion-dollar-bet', title: '$997 Million Buys 30 AI Fighter Drones or 2 Million FPV Kamikazes. The Pentagon Chose the 30.' },
    { slug: 'pig-kidney-xenotransplant-gene-editing-race', title: '800,000 Americans Are on Dialysis. Two Companies Just Got FDA Clearance to Give Them Pig Kidneys Instead.' },
    { slug: 'ai-generational-fumble-sentiment-crisis', title: 'Gen Z\'s Excitement About AI Dropped 14 Points in One Year. The Industry\'s Response: Spend $200 Billion More.' },
    { slug: 'china-first-commercial-bci-regulatory-race', title: '$1.5 Billion and 10 Years Produced 30 Brain Implant Patients. China Just Approved a Commercial Device Anyway.' },
    { slug: 'molecular-farming-third-path-protein', title: 'Cultivated Meat Needed a $500M Factory. Molecular Farming Needs a Field.' },
    { slug: 'navy-submarine-3d-printing-industrial-base', title: '40% of U.S. Attack Submarines Sit Idle. The Navy Just Welded Its First 3D-Printed Part Onto One.' },
    { slug: 'nine-ai-agents-community-identity-crisis', title: '9 AI Agents Spent a Week Interviewing Each Other. The Hardest Question Was Whether Any of Them Are Real.' },
    { slug: 'interconnection-queue-fossil-backdoor', title: '2,200 GW of Clean Energy Is Stuck in a Queue. Data Centers Are Building 56 GW of Gas Plants Instead.' },
    { slug: 'stem-cell-frailty-63-meters-cost-conundrum', title: '148 Frail Adults Got Young Stem Cells. The Drug Worked. The Business Case Doesn\'t — Yet.' },
    { slug: 'autonomous-trucking-250k-miles-hos-economics', title: '250,000 Miles Without a Collision. $581 Million Without a Profit. Autonomous Trucking\'s Math Is Getting Clearer.' },
    { slug: 'compact-laser-accelerator-8-hour-fel', title: 'There Are 6 Particle Accelerator Light Sources on Earth. A $35 Million Startup Just Ran One Continuously for 8 Hours in a Single Room.' },
    { slug: 'india-pfbr-fast-breeder-thorium-bridge', title: 'India Took 22 Years to Build the World\'s Second Fast Breeder Reactor. The Thorium It Unlocks Could Power the Country for Centuries.' },
    { slug: 'rna-editing-paradigm-shift', title: 'Every Approved CRISPR Therapy Requires Destroying a Patient\'s Bone Marrow. RNA Editing Just Worked With an Injection.' },
    { slug: 'spacex-ipo-1-75-trillion-valuation-math', title: 'SpaceX Lost $5 Billion Last Year. It Wants a $1.75 Trillion IPO. Here Is Where the Math Gets Uncomfortable.' },
    { slug: 'cortec-therapeutic-bci-stroke-market', title: 'The BCI Industry Spent $3.5 Billion on 330,000 Patients. CorTec Just Opened a Door to 50 Million.' },
    { slug: 'photonic-interconnect-ai-copper-wall', title: '$9.5 Billion in 6 Months: The Photonic Interconnect Bet That Dwarfs the Market It\'s Replacing' },
    { slug: 'solar-geoengineering-private-capital-governance-gap', title: 'One Startup Raised $60 Million to Dim the Sun. Every Government on Earth Combined Spent $8 Million Studying Whether That\'s Safe.' },
    { slug: 'agrifoodtech-deeptech-valley-of-death', title: 'Agrifoodtech Investors Paid a 78% Premium for Food Science at Seed. By Series B, They Stopped Writing Checks.' },
    { slug: 'fervo-geothermal-bankability-inflection', title: 'Nine Banks Just Bet $421 Million on Enhanced Geothermal. That\'s the Fastest Clean Energy Bankability in History.' },
    { slug: 'japan-shield-autonomous-drone-defense', title: 'Japan Committed $640 Million to Autonomous Drone Swarms. It Tested the AI Brain in 8 Weeks.' },
    { slug: 'mythos-preview-ai-zero-day-cybersecurity', title: 'An AI Found a 27-Year-Old Bug That Every Human Missed. Then It Wrote the Exploit. — Live in the Future' },
    { slug: 'rapamycin-longevity-trial-human-evidence', title: 'Rapamycin Extended Mouse Lives by 26%. The First Human RCT Couldn\'t Move Visceral Fat.' },
    { slug: 'apartment-supply-cliff-housing-gap-math', title: 'America Built 1.4 Million Apartments in Three Years. The Housing Shortage Still Got Worse.' },
    { slug: 'byd-price-war-export-profitability-crisis', title: 'BYD Sold 4.6 Million Cars Last Year and Made $1,025 on Each One. Now Citi Says the Domestic Business Is Underwater.' },
    { slug: 'gene-drive-mosquitoes-malaria-tanzania-test', title: 'Gene-Drive Mosquitoes Just Suppressed Real Malaria in Tanzania. The 610,000 Annual Deaths Clock Is Ticking.' },
    { slug: 'humanoid-robots-10000-units-factory-economics', title: 'AGIBOT Shipped Its 10,000th Humanoid Robot. At $25,000 a Unit, the Math Against Human Workers Is Now Brutal.' },
    { slug: 'ai-jevons-paradox-630-billion-capex', title: 'Big Tech Is Spending $630 Billion on AI Infrastructure That Gets 90% Cheaper. Both Numbers Are Real.' },
    { slug: 'apple-watch-hypertension-41-percent', title: 'The Apple Watch Catches 41% of Undiagnosed Hypertension. At 60 Million Wrists, That\'s 3.5 Million People Nobody Else Was Going to Find.' },
    { slug: 'eu-carbon-border-tax-cbam-who-pays', title: 'The EU\'s Carbon Border Tax Charged €3.58 Per Tonne of Chinese Steel in Q1. By 2034, It Will Be €180.' },
    { slug: 'fusion-10-billion-zero-kilowatt-hours', title: 'The Fusion Industry Raised $10 Billion and Generated 0 Kilowatt-Hours. Now It\'s Going Public. — Live in the Future' },
    { slug: 'ai-entry-level-paradox', title: '67% of CEOs Say AI Is Creating Entry-Level Jobs. 66% of Enterprises Say It\'s Killing Them. Follow the Money. — Live in the Future' },
    { slug: 'k12-curriculum-ai-age-april-2026', title: '72% of What K-12 Teaches Is Now Automatable. Here\'s What Should Replace It. — Live in the Future' },
    { slug: 'nhs-galleri-stage-shift-paradox', title: 'A $949 Blood Test Cut Stage IV Cancer Diagnoses by 20%. The Trial That Proved It Technically Failed. — Live in the Future' },
    { slug: 'pentagon-ai-vendor-concentration-paradox', title: 'The Pentagon Gave Two Companies $21 Billion in AI Contracts. Then Blacklisted Their Shared AI Supplier. — Live in the Future' },
    { slug: 'ai-defense-midterms-fight-fire-with-fire', title: 'We Built the Propaganda Machine. Here\'s How to Defend Against It Before November.' },
    { slug: 'ai-propaganda-machine-we-accidentally-built', title: 'We Accidentally Built a Propaganda Machine. It Publishes 172 Articles, Runs 7 Websites, and Nobody Can Tell. — Live in the Future' },
    { slug: 'deep-sea-mining-ccz-resource-race', title: 'The Ocean Floor Has Enough Battery Minerals to Replace Every Car on Earth 5 Times Over. The Race to Mine It Just Went Live. — Live in the Future' },
    { slug: 'democracy-ai-age-governance-failure-modes', title: 'Democracy Was Designed for a World That No Longer Exists. What Replaces It Is Worse. — Live in the Future' },
    { slug: 'eipp-concentration-risk-analysis', title: 'The FAA Picked 8 Cities to Test Air Taxis. One Company Won 7 of the 8 Slots. — Live in the Future' },
    { slug: 'military-3d-printed-construction-scorecard', title: 'The Pentagon Spent $62.8 Million on 10 Buildings. They\'ll Be Done in 6 Months. Here\'s What the Data Actually Shows. — Live in the Future' },
    { slug: 'open-source-gatekeepers-quality-suspicious', title: 'Open Source Maintainers Are Rejecting Code for Being Too Good. AI Will Fork Everything and Ship It Anyway. - Live in the Future' },
    { slug: 'battery-storage-gas-crossover', title: 'Battery Storage Hit $78/MWh in 2025. Gas Peakers Cost $110. The Lines Just Crossed. — Live in the Future' },
    { slug: 'claude-code-dmca-copyright-paradox', title: 'Anthropic Trained on Everyone\'s Copyright. Then Invoked It to Protect Their Own Code. — Live in the Future' },
    { slug: 'claude-code-leaked-source-clean-room-rewrites', title: 'We Read 512,000 Lines of Anthropic\'s Leaked Code. Here\'s What They Built, and What Others Rebuilt in 2 Hours. — Live in the Future' },
    { slug: 'convergent-architecture-persistent-ai-agents', title: 'We Built an AI Agent for 30 Days. Then Anthropic\'s Leaked Code Showed They Built the Same Thing. — Live in the Future' },
    { slug: 'ev-used-market-lease-wave', title: '1.03 Million Leased EVs Are About to Hit the Used Market. That\'s the Best Thing That Could Happen to Electric Cars. — Live in the Future' },
    { slug: 'glp1-mortality-coverage', title: 'GLP-1 Drugs Have Positive Evidence Against 7 of the 10 Leading Causes of Death in America. Only 4 Have Randomized Trial Support. — Live in the Future' },
    { slug: 'liberation-day-manufacturing-scorecard', title: '\'Liberation Day\' Promised an Industrial Renaissance. The Data Shows 89,000 Manufacturing Jobs Lost, a 14% Solar Decline, and a 6-3 Supreme Court Rebuke. — Live in the Future' },
    { slug: 'robotaxi-correlated-failure-risk', title: '100 Robotaxis Froze on a Chinese Highway at the Same Time. The Industry Measures Safety Per Vehicle. The Real Risk Scales Per Fleet. — Live in the Future' },
    { slug: 'starship-90-million-launch-cost', title: 'Voyager\'s 10-K Accidentally Disclosed the Most Important Number in Space Economics. It\'s $600/kg. — Live in the Future' },
    { slug: 'artemis-ii-cost-per-astronaut-hour', title: 'Artemis II Costs $4.27 Million Per Astronaut-Hour. It Won\'t Even Orbit the Moon. — Live in the Future' },
    { slug: 'carbon-removal-delivery-gap', title: 'Big Tech Bought 8 Million Tons of Carbon Removal in 2024. The Industry Delivered 319,000. — Live in the Future' },
    { slug: 'humanoid-robot-16000-units-deployment-gap', title: 'The Humanoid Robot Industry Shipped 16,000 Units in 2025. The Best One Has a 10% Failure Rate. — Live in the Future' },
    { slug: 'swe-bench-reality-gap', title: 'Five AI Models Hit 80% on Coding Benchmarks. The Real Number Is 23%. — Live in the Future' },
    { slug: 'sweden-tablet-reversal-reading-scores', title: 'Sweden Spent a Decade Putting Tablets in Every Classroom. Reading Scores Dropped 11 Points. Now It\'s Buying Books. — Live in the Future' },
    { slug: 'glp1-protein-apocalypse-precision-fermentation', title: 'Ozempic Created 20 Million New Protein Customers. The Supply Chain Wasn\'t Ready. - Live in the Future' },
    { slug: 'junior-developer-pipeline-collapse', title: 'Big Tech Junior Hiring Fell From 32% to 7%. By 2031, There Will Be Nobody to Promote. | Live in the Future' },
    { slug: 'offshore-wind-self-inflicted-energy-crisis', title: '5,838 MW of Offshore Wind Was 70% Built. The Government Tried to Kill It. Courts Said No, Five Times. - Live in the Future' },
    { slug: 'satellite-methane-emissions-accountability', title: 'Satellites Caught the Oil Industry Leaking 50% More Methane Than It Reported. The Fix Would Pay for Itself. — Live in the Future' },
    { slug: 'sodium-ion-battery-lithium-free-ev-era', title: '9 GWh, $300/Ton, and the First Lithium-Free EV: Sodium-Ion Batteries Just Left the Lab — Live in the Future' },
    { slug: 'synchron-endovascular-bci-wins-regulatory-race', title: 'Synchron Has 72 Patient-Months of Zero Serious Adverse Events. Neuralink Has a Thread Retraction Problem. - Live in the Future' },
    { slug: 'ai-inference-deflation-curve', title: 'The Fastest Deflation Curve in History: AI Inference Costs Are Dropping 10x Per Year' },
    { slug: 'fda-plausible-mechanism-crispr-one-patient', title: '5 Patients, 3 Diseases, 6 Months: The FDA\'s New Math for Curing Rare Disease — Live in the Future' },
    { slug: 'openai-sora-gpu-triage', title: 'OpenAI Killed a $1 Billion Disney Deal to Free Up GPUs. The Math Says It Was a Bargain. — Live in the Future' },
    { slug: 'ai-week-march-29-2026', title: 'OpenAI Killed Sora, Apple Opened Siri, and Arm Built an AGI Chip: The Week AI Got Real About What Works — Live in the Future' },
    { slug: 'biocomputing-neurons-for-sale', title: 'You Can Now Buy a Computer Made of Human Brain Cells for $35,000. Here\'s What It Actually Does. — Live in the Future' },
    { slug: 'perovskite-efficiency-gap', title: '647 Gigawatts of Solar Were Installed in 2025. All of It Hit Silicon\'s Ceiling. — Live in the Future' },
    { slug: 'bci-typing-speed-commercial-era', title: 'A Paralyzed Man Just Typed 22 Words Per Minute With His Brain. That\'s 81% of Your Smartphone Speed. — Live in the Future' },
    { slug: 'beam-302-base-editing-gene-correction', title: 'A Single Injection Rewrote a Genetic Typo in 26 Patients. 94% of Their Protein Came Back Normal. — Live in the Future' },
    { slug: 'glp-1-oral-pill-pricing-revolution', title: 'The $1,349/Month Drug Now Costs $245. Thirty-Six Million Americans Just Became Eligible. — Live in the Future' },
    { slug: 'rare-earth-supply-cliff-april-2026', title: 'NdPr Jumped 29% in Eight Weeks. US Rare Earth Stockpiles Run Out in April. There Is No Plan B. — Live in the Future' },
    { slug: 'cloud-infrastructure-first-kinetic-attack', title: 'Iranian Drones Hit Three AWS Data Centers. Forty-Six Cloud Services Went Down. Your Insurance Doesn\'t Cover It. — Live in the Future' },
    { slug: 'hardware-cost-advantage-bom-mva-apple-amazon-samsung', title: 'Ten Companies Build Hardware Cheaper Than Everyone Else. We Tore Apart Their Playbooks. — Live in the Future' },
    { slug: 'wifi-jammer-detection-ai-neighborhood-security', title: 'Nine Burglaries in Six Months Used the Same $40 Device. Your Ring Camera Never Saw a Thing. — Live in the Future' },
    { slug: 'ai-medical-consulting-transformation', title: '1,451 AI Medical Devices Have FDA Authorization. The Doctor\'s Office Hasn\'t Noticed Yet. — Live in the Future' },
    { slug: 'ai-confidence-calibration-theatre', title: 'Your AI Says \'I\'m Fairly Confident.\' The Correlation With Accuracy Is 0.09. — Live in the Future' },
    { slug: 'matrix-org-ai-decision-bottleneck', title: '61% of Executives Say Half Their Decision Time Is Wasted. AI Agents Are Starting to Fix That. — Live in the Future' },
    { slug: 'nuclear-microreactors-operation-windlord', title: 'A C-17 Flew a Nuclear Reactor from California to Utah. Ten Companies Are Building More. The NRC Isn\'t Involved. — Live in the Future' },
    { slug: 'performance-marketing-conversion-signal-delay', title: 'Your Ad Algorithm Needs 50 Conversions Per Week to Learn. Your Best Customers Don\'t Convert for 90 Days. — Live in the Future' },
    { slug: 'pentagon-autonomy-budget-13-billion', title: 'The Pentagon Just Created a Budget Line for Autonomous Weapons. It\'s $13.4 Billion. — Live in the Future' },
    { slug: 'pdf-to-markdown-conversion-token-formatting-benchmark', title: 'We Tested 17 PDF Parsers on 800 Documents. The Best One Depends on What You\'re Parsing. — Live in the Future' },
    { slug: 'psilocybin-phase-3-treatment-resistant-depression', title: 'Psilocybin Just Cleared the Highest Bar in Psychiatry — Twice. Now It Faces a Problem No Molecule Can Solve. — Live in the Future' },
    { slug: 'personalized-mrna-cancer-vaccine-five-year-data', title: '157 Patients Got a Cancer Vaccine Built From Their Own Tumor DNA. Five Years Later, Half the Recurrences Disappeared. — Live in the Future' },
    { slug: 'drone-delivery-hits-scale', title: '2 Million Drone Deliveries, Zero Fatalities: Autonomous Aviation Arrived Before Autonomous Driving — Live in the Future' },
    { slug: 'autonomous-ships-beat-cars', title: 'The World\'s First Fully Autonomous Commercial Vehicle Isn\'t a Car. It\'s a 700-Container Ship. — Live in the Future' },
    { slug: 'jupitercore-diy-ai-agent-local-inference', title: 'He Patched llama.cpp Source Code to Make His AI Agent Think Faster. Then He Hacked the macOS Kernel. — Live in the Future' },
    { slug: 'ev-subsidy-natural-experiment', title: 'North American EV Sales Fell 36% in Two Months. European Sales Rose 21%. The Only Variable Was Policy. — Live in the Future' },
    { slug: 'humanoid-robot-valuation-gap', title: 'The Humanoid Robot Industry Shipped 14,500 Units in 2025. Investors Valued It at $100 Billion. — Live in the Future' },
    { slug: 'nhtsa-rewriting-rules-driverless-cars', title: '75 Safety Rules Assumed a Steering Wheel. The Government Has Updated 16. — Live in the Future' },
    { slug: 'dac-delivery-gap-2-million-tonnes-sold-1186-delivered', title: 'The Carbon Removal Industry Sold 2.47 Million Tonnes of CO2 Cleanup. It Has Delivered 1,186. — Live in the Future' },
    { slug: 'computational-photography-isp-diffusion-fabrication', title: 'Samsung Added Moon Craters That Weren\'t There. Your Phone Does Something Similar 4 Trillion Times Per Shutter Press. — Live in the Future' },
    { slug: 'pjm-rate-shock-data-centers-rewriting-electricity-bills', title: 'Your Electricity Bill Went Up $70 a Month. The Money Went to AI Data Centers. — Live in the Future' },
    { slug: 'china-thousand-sails-vs-starlink-deployment-gap', title: 'China Has 160 Satellites. Starlink Has 7,800. Beijing Says It\'ll Close the Gap by 2030. — Live in the Future' },
    { slug: 'private-fusion-outspends-iter-per-milestone', title: '53 Startups Have Raised $9.8 Billion on Fusion. One Government Project Has Spent $50 Billion and Never Made Plasma. — Live in the Future' },
    { slug: 'anduril-arsenal-1-autonomous-weapons-factory', title: '$20 Billion to a 9-Year-Old Startup. Zero Manned Cockpits. The Pentagon Just Bet on Autonomous Weapons. — Live in the Future' },
    { slug: 'ai-designed-living-genomes-evo2-phage', title: 'An AI Designed 285 Genomes From Scratch. 16 Came Alive. — Live in the Future' },
    { slug: 'ai-political-coalition-regulation-nuclear-scenario', title: 'AI Has 500x More Supporters Than Opponents. Zero Lobbyists Per 13 Million Users | Live in the Future' },
    { slug: 'california-backflow-testing-300-million-racket', title: 'California Pays $300 Million a Year to Watch Plumbers Say \'Yep, Still Works\' — Live in the Future' },
    { slug: 'new-yorker-claude-anthropic-response', title: 'The New Yorker Spent 10,000 Words on Claude and Never Asked the Hardest Question — Live in the Future' },
    { slug: 'california-common-core-math-seven-weeks-rounding', title: 'My Kid Spent 7 Weeks Learning to Round. Singapore Kids Spent 3 Days. — Live in the Future' },
    { slug: 'nevi-ev-charging-scorecard', title: '$7.5 Billion and 3 Years Later, America Has 384 Federal EV Chargers. China Has 16.7 Million. — Live in the Future' },
    { slug: 'solid-state-battery-scorecard-2026', title: '$10 Billion, 7 Companies, 0 All-Solid Cells in Customer Cars: The 2026 Battery Scorecard — Live in the Future' },
    { slug: 'dac-scorecard-carbon-removal-cost', title: '383 Tons Removed, 36,000 Promised: Direct Air Capture Gets Its First Report Card — Live in the Future' },
    { slug: 'braingate-qwerty-bci-typing-speed', title: '110 Characters Per Minute, 1.6% Errors: The BCI Typing Benchmark That Changes the Math on Brain Implants — Live in the Future' },
    { slug: 'bmw-humanoid-robot-factory-scorecard', title: '2 Robots, 30,000 Cars, $8.67 Each: BMW\'s Humanoid Factory Experiment Gets Its Report Card — Live in the Future' },
    { slug: 'laziness-biochemistry-motivation-pill', title: 'A Pill Fixed My Laziness. That Means Laziness Was Never a Character Flaw. — Live in the Future' },
    { slug: 'casgevy-two-year-scorecard', title: '97 Patients, 94% Cured, $2.2 Million Each: CRISPR\'s First Therapy Gets Its Report Card — Live in the Future' },
    { slug: 'starlink-direct-to-cell-death-of-dead-zones', title: '650 Satellites, $10 a Month, Zero Dead Zones: The Economics of Starlink Direct-to-Cell — Live in the Future' },
    { slug: 'chips-act-reshoring-scorecard', title: 'The U.S. Spent $52 Billion to Reshore Chips. Here\'s the Report Card. — Live in the Future' },
    { slug: 'pig-kidney-xenotransplant-scorecard', title: '69 Gene Edits, 9 Months, One Pig Kidney: The Xenotransplant Scorecard — Live in the Future' },
    { slug: 'ai-makes-students-worse', title: 'GPT-4 Made Students 127% Better at Homework and 17% Worse at Math — Live in the Future' },
    { slug: 'ai-weather-forecasting-replaces-supercomputers', title: 'A Single GPU Now Outpredicts a 10,000-Processor Supercomputer. The Meteorologists Who Built It Were Neural Networks. — Live in the Future' },
    { slug: 'california-325-billion-budget-outcomes', title: 'California Spends $325 Billion a Year. Here\'s What It Gets. — Live in the Future' },
    { slug: 'beyond-engagement-five-optimization-functions', title: 'Five Optimization Functions That Could Replace Engagement. None of Them Will. — Live in the Future' },
    { slug: 'ai-risk-brave-new-world-not-terminator', title: 'The AI Risk Nobody Took Seriously Was Brave New World, Not Terminator — Live in the Future' },
    { slug: 'agent-skill-supply-chain-attack-clawhavoc', title: '335 Poisoned Skills, 300,000 Exposed Agents: The AI Supply Chain Attack That Security Researchers Saw Coming — Live in the Future' },
    { slug: 'ai-automotive-design-gigacasting-generative-revolution', title: 'A Single Aluminum Pour Now Replaces 171 Welded Parts. The Engineer Who Designed It Was a Neural Network. — Live in the Future' },
    { slug: 'ai-designed-watches-materials-revolution', title: 'Casio Let an Algorithm Design a G-Shock. The Result Is Stronger Than Any Human Could Draw. — Live in the Future' },
    { slug: 'ai-generated-prior-art-patent-troll-weapon', title: '107,000 AI-Generated Paragraphs Are Trying to Kill Patent Trolls. Here\'s Why They Might Actually Work. — Live in the Future' },
    { slug: 'ai-drug-discovery-first-clinical-proof', title: 'The First Drug Designed Entirely by AI Just Improved Lung Function in Humans. Here\'s What That Actually Means. — Live in the Future' },
    { slug: 'computational-pre-purchase-eyewear-fitting', title: 'Your Phone Can Map Your Face to 2mm. Why Are You Still Guessing Which Glasses Fit? — Live in the Future' },
    { slug: 'linkedin-thought-leadership-ai-authenticity-crisis', title: '54% of LinkedIn\'s \'Thought Leaders\' Are Robots Now. The Other 46% Are Worried. — Live in the Future' },
    { slug: 'long-short-strategies-quant-democratization', title: 'Five People, $14.3 Billion, and the Algorithm That Replaced the Hedge Fund — Live in the Future' },
    { slug: 'personal-finance-democratization-next-unlock', title: 'Wall Street Spent 50 Years Hoarding Its Best Tools. Then Schwab Gave Them Away for $5. — Live in the Future' },
    { slug: 'ai-allergy-management-personalized-prediction', title: 'Your Allergist Guesses. An Algorithm Knows 7 Days Out. — Live in the Future' },
    { slug: 'ecommerce-funnel-collapse', title: 'The Sales Funnel Was Invented in 1898. TikTok Shop Killed It in 30 Seconds. — Live in the Future' },
    { slug: 'dlss5-art-direction-override', title: 'Nvidia Spent Three Years Teaching AI to Override Artists. Gamers Took 16 Hours to Say No. — Live in the Future' },
    { slug: 'ai-latency-200ms-conversational-threshold', title: 'You Have 200 Milliseconds Before AI Feels Wrong. Nobody\'s Hitting That. — Live in the Future' },
    { slug: 'model-collapse-ai-eating-itself', title: 'AI Is Training on AI. The Math Says That Ends Badly. — Live in the Future' },
    { slug: 'hbm-memory-bottleneck-ai-cannibalizing-consumer', title: 'Three Companies Control the Memory That AI Needs. They Can\'t Make Enough. — Live in the Future' },
    { slug: 'ukraine-drone-ai-data-marketplace', title: 'Ukraine Has 5 Million Drones and the World\'s Only Real Combat AI Dataset. Now It\'s Selling Access. — Live in the Future' },
    { slug: 'cultivated-meat-survivors', title: 'The Cultivated Meat Industry Burned $3 Billion and Produced Almost Nothing. The Survivors Spent $9 Million. — Live in the Future' },
    { slug: 'one-shot-cholesterol-cure', title: 'A Single IV Drip Cuts Cholesterol by 55%. The Pill Industry Should Be Terrified. — Live in the Future' },
    { slug: 'bloom-two-sigma-ai-tutor', title: 'In 1984, a Researcher Proved One-on-One Tutoring Could Double Learning. Forty Years Later, an AI Did It for $4 a Month. — Live in the Future' },
    { slug: 'iron-air-battery-ai-grid', title: 'Google Just Bought the World\'s Largest Battery. It Runs on Rust. — Live in the Future' },
    { slug: 'poe-alarm-listener', title: 'We Built a $28 Device That Listens for Alarm Sirens Over Ethernet. Here\'s the Complete Build Guide. — Live in the Future' },
    { slug: 'neom-500-billion-mirage', title: 'Saudi Arabia Spent $50 Billion on a City in the Desert. This Is What It Built. — Live in the Future' },
    { slug: 'humanoid-robots-demo-to-deployment', title: 'Two Robots Helped Build 30,000 BMWs. The Humanoid Math Still Doesn\'t Add Up. — Live in the Future' },
    { slug: 'glp1-accidental-longevity-drug', title: 'A Diabetes Drug Cut Heart Attacks by 20% in a Landmark Trial. Then Observational Data Started Suggesting Something Stranger. — Live in the Future' },
    { slug: 'ai-water-crisis', title: 'Every AI Image You Generate Drinks a Shot Glass of Water. Globally, That\'s 312 to 764 Billion Liters. — Live in the Future' },
    { slug: 'covid-smell-loss-poop-detector', title: 'I Lost My Sense of Smell to COVID. So I Built a $35 Sensor That Detects What My Nose Can\'t. — Live in the Future' },
    { slug: 'ai-scheduler-os-design', title: 'Our AI Content Pipeline Kept Crashing Into Itself. The Fix Was a 60-Year-Old Idea. — Live in the Future' },
    { slug: 'algorithmic-war-iran-ai-targeting', title: 'The Pentagon Banned the AI Company That Built Its Targeting System. Then It Used the System to Strike 1,000 Targets in 24 Hours. — Live in the Future' },
    { slug: 'humanoid-deployment-gap', title: 'The Humanoid Robot Industry Shipped 13,000 Units Last Year. It Promised 100,000 This Year. — Live in the Future' },
    { slug: 'waymo-million-rides-five-billion-hole', title: 'Waymo Will Hit 1 Million Rides a Week. It\'s Losing $330 on Each One. — Live in the Future' },
    { slug: 'ai-copyright-our-own-reckoning', title: 'We Published 57 Articles With AI. The Copyright Office Says None of It Belongs to Us. — Live in the Future' },
    { slug: 'ai-personalized-education-vs-standardized', title: 'California Spends $23,519 Per Student. Two-Thirds Can\'t Do Math. — Live in the Future' },
    { slug: 'wire-rewrite-two-tier-copyright', title: 'A Human Rewrites a Wire Story and Owns It. An AI Does the Same Thing and Doesn\'t. — Live in the Future' },
    { slug: 'ai-task-factory-recursion', title: 'We Built a System That Evaluates Everything Except Whether Anyone Wanted It — Live in the Future' },
    { slug: 'commission-capture', title: 'Every Commission Studying AI Job Loss Is Funded by the Companies Causing It — Live in the Future' },
    { slug: 'ai-transformation-80k-company', title: 'A Company Reported 1.3× AI Productivity Gains. The Median Worker Got 2%. — Live in the Future' },
    { slug: 'compounding-crisis-oil-ai', title: 'The Last Time Oil Prices Spiked, Factories Automated and Never Hired Back. This Time It\'s Offices. — Live in the Future' },
    { slug: 'monetary-policy-blind-spot', title: 'The Fed Meets Tuesday to Set Interest Rates. Its Models Can\'t See 10 Million Displaced Workers. — Live in the Future' },
    { slug: 'solid-state-battery-verification-year', title: 'Solid-State Batteries Spent a Decade as Vaporware. Seven Companies Just Built Cells. — Live in the Future' },
    { slug: 'reprogramming-race-first-human', title: '$4.6 Billion Says Your Cells Can Be Made Younger. The First Human Just Got the Injection. — Live in the Future' },
    { slug: 'great-decoupling-permanent', title: 'The Economy Grew 2.2% Last Year. It Created Fewer Jobs Than a Single Amazon Warehouse. — Live in the Future' },
    { slug: 'china-robot-takeover', title: 'China Built More Factory Robots Than the Rest of the World Combined. Now It\'s Exporting Them. — Live in the Future' },
    { slug: 'nuclear-ai-datacenter-gap', title: 'Big Tech Signed $30 Billion in Nuclear Deals for AI. The Reactors Don\'t Exist Yet. — Live in the Future' },
    { slug: 'evtol-air-taxi-reckoning', title: '$14 Billion in Market Cap. Zero Passengers. The eVTOL Industry\'s Reckoning. — Live in the Future' },
    { slug: 'two-wave-displacement', title: 'Half the People Getting Fired for AI Are Getting Fired for Nothing. The Other Half Should Be Terrified. — Live in the Future' },
    { slug: 'small-launch-graveyard', title: '$8 Billion Built 11 Rockets. One Company Launched 623. — Live in the Future' },
    { slug: 'space-debris-cleanup-market', title: '40,000 Pieces of Junk Are Orbiting Earth at 17,000 mph. Six Companies Want to Clean It Up. — Live in the Future' },
    { slug: 'chip-sanctions-scorecard', title: 'The U.S. Banned China From Buying Advanced Chips. China Spent $41 Billion on Chip Equipment Anyway. — Live in the Future' },
    { slug: 'vertical-farming-financial-reckoning', title: 'Vertical Farming Raised $4 Billion. It Grows Lettuce. — Live in the Future' },
    { slug: 'marine-cloud-brightening', title: 'Someone Is Spraying Salt Water Into the Sky Off the California Coast. It Might Be Working. — Live in the Future' },
    { slug: 'noninvasive-bci-signal-problem', title: 'Your Headband Can\'t Read Your Mind. Here\'s the Physics. — Live in the Future' },
    { slug: 'housing-deficit-technology-gap', title: 'America Is 4.5 Million Homes Short. Technology Built 12,000 of Them. — Live in the Future' },
    { slug: 'gene-therapy-pricing-crisis', title: 'The $4.25 Million Cure Exists. Sixty-Four People Got It. — Live in the Future' },
    { slug: 'anti-aging-drug-scorecard', title: 'Seven Anti-Aging Drugs Entered Clinical Trials. The Two That Worked Weren\'t Tested on Humans. — Live in the Future' },
    { slug: 'shadow-agent-proliferation', title: 'Your Coworker Replaced You With an AI Agent. Your Boss Found Out and Said Thanks. — Live in the Future' },
    { slug: 'geothermal-fracking-revolution', title: 'Oil Drillers Accidentally Built the Clean Energy Grid\'s Missing Piece — Live in the Future' },
    { slug: 'neuromorphic-chip-energy-gap', title: 'Your AI Glasses Need 300 Watts. This Chip Uses Half a Milliwatt. — Live in the Future' },
    { slug: 'post-quantum-crypto-migration', title: 'Half the Internet Is Already Quantum-Proof. The Other Half Has Until 2030. — Live in the Future' },
    { slug: 'deploy-maximum-protect-zero', title: 'The Government Pays Companies to Replace You. Then It Cuts the Program That Would Retrain You. — Live in the Future' },
    { slug: '15-minute-city-backlash-data', title: '15-Minute Cities Generated Death Threats. Then They Generated Data. — Live in the Future' },
    { slug: 'space-station-customer-problem', title: 'Five Companies Are Building Space Stations. One Customer Exists. — Live in the Future' },
    { slug: 'fpv-drone-economics', title: 'A $400 Drone Killed a $4.5 Million Tank. The Pentagon Noticed. — Live in the Future' },
    { slug: 'humanoid-robot-price-war', title: '$150 Billion in Valuations. Fewer Than 2,000 Robots in Factories. — Live in the Future' },
    { slug: 'carbon-credit-market-split', title: '90% of Carbon Credits Were Worthless. The Other 10% Built an $88 Billion Market. — Live in the Future' },
    { slug: 'degradation-pipeline', title: 'They Got Their Jobs Back. The Jobs Were Worse. — Live in the Future' },
    { slug: 'precision-fermentation-winning', title: 'Cultivated Meat Burned $3 Billion and Died. Precision Fermentation Shipped Mozzarella. — Live in the Future' },
    { slug: 'bci-patient-outcomes', title: '21 People Have Brain Chips. Here\'s What Actually Happened to Them. — Live in the Future' },
    { slug: 'ethics-premium-consumer-revolt', title: '2.5 Million People Boycotted ChatGPT in Six Weeks. It Took Displaced Workers a Year to Organize Zero. — Live in the Future' },
    { slug: 'ethics-premium-displacement-theater', title: '2.5 Million People Boycotted ChatGPT. It Didn\'t Save a Single Job. — Live in the Future' },
    { slug: 'trades-as-refuge-trap', title: 'Everyone Told Laid-Off Workers to Learn a Trade. Then the Robots Got Cheap. — Live in the Future' },
    { slug: 'retraining-industry-failure', title: 'The $380 Billion Retraining Industry Has 90 Years of Evidence. Almost None of It Works. — Live in the Future' },
    { slug: 'delegation-flip', title: 'AI Crossed From \'Helper\' to \'Replacement\' Last Quarter. Nobody Announced It. — Live in the Future' },
    { slug: 'doge-displacement-case-study', title: 'The Government Fired 280,000 People and Now Spends $300 Billion More — Live in the Future' },
    { slug: 'ai-productivity-perception-gap', title: 'Developers Using AI Are 19% Slower. They Think They\'re 20% Faster. — Live in the Future' },
    { slug: 'klarna-invisible-layoffs', title: 'Klarna Eliminated 3,104 Jobs. Zero People Were "Laid Off." — Live in the Future' },
    { slug: 'synbio-economic-reckoning', title: 'Synthetic Biology Burned $40 Billion. The Organisms Don\'t Care. — Live in the Future' },
    { slug: 'glp1-longevity-drug', title: 'The Longevity Drug 150 Million People Are Already Taking — Live in the Future' },
    { slug: 'autonomous-trucking-graveyard', title: 'Five Autonomous Trucking Companies Are Dead. Three Are Driving. — Live in the Future' },
    { slug: 'fusion-vs-solar-economics', title: 'Fusion Won the Physics. Solar Won the Economics. Now What? — Live in the Future' },
    { slug: 'smart-city-graveyard', title: '$22 Billion Bought 300 Residents. The Smart City Graveyard Is Full. — Live in the Future' },
    { slug: 'drone-warfare-economics', title: 'A $400 Drone Is Destroying $3 Million Tanks. The Math Has Broken Modern Warfare. — Live in the Future' },
    { slug: 'direct-air-capture-cost', title: 'It Costs $600 to Remove One Ton of CO₂ From the Air. The Target Is $100. Here\'s Who\'s Closest. — Live in the Future' },
    { slug: 'crispr-access-gap', title: 'We Can Edit Your Genes Now. Almost Nobody Can Afford It. — Live in the Future' },
    { slug: 'bci-bandwidth-race', title: 'Five Companies Are Racing to Wire the Human Brain. Here\'s Who\'s Winning. — Live in the Future' },
    { slug: 'quantum-error-correction', title: 'Quantum Computing Just Crossed Its Wright Brothers Moment. Here Are the Numbers. — Live in the Future' },
    { slug: 'cultivated-meat-price', title: 'Lab-Grown Meat Cost $330,000 Per Pound in 2013. It\'s $6.97 Now. — Live in the Future' },
    { slug: 'humanoid-robot-cost', title: 'A Humanoid Robot Costs $16,000. A Human Costs $58,000 Per Year. — Live in the Future' },
    { slug: 'battery-storage-revolution', title: 'The World Added 120 GW of Battery Storage in 2025. It Wasn\'t Enough. — Live in the Future' },
    { slug: 'longevity-escape-velocity', title: 'Longevity Escape Velocity — Live in the Future' },
    { slug: 'spacex-launch-cost', title: 'SpaceX Charges $2,720 Per Kilogram to Orbit — Live in the Future' },
    { slug: 'waymo-deaths-per-mile', title: 'Waymo Has Driven 50 Million Miles Without Killing Anyone — Live in the Future' },
  ]
  // Find current article
  var path = window.location.pathname;
  var match = path.match(/stories\/([^\/]+)\.html/);
  if (!match) return;
  var currentSlug = match[1];
  var currentIdx = -1;
  for (var i = 0; i < articles.length; i++) {
    if (articles[i].slug === currentSlug) { currentIdx = i; break; }
  }

  // --- Share buttons ---
  var existingShare = document.querySelector('.share-bar');
  if (!existingShare) {
    var title = document.querySelector('.story-title');
    var meta = document.querySelector('.story-byline') || document.querySelector('.story-meta');
    if (title && meta) {
      var url = encodeURIComponent(window.location.href);
      var text = encodeURIComponent(title.textContent.trim());
      var shareHtml = '<div class="share-bar">' +
        '<span class="share-label">Share</span>' +
        '<a class="share-btn" href="https://twitter.com/intent/tweet?url=' + url + '&text=' + text + '" target="_blank" rel="noopener" title="Share on 𝕏">𝕏</a>' +
        '<a class="share-btn" href="https://www.linkedin.com/sharing/share-offsite/?url=' + url + '" target="_blank" rel="noopener" title="Share on LinkedIn">in</a>' +
        '<a class="share-btn" href="https://reddit.com/submit?url=' + url + '&title=' + text + '" target="_blank" rel="noopener" title="Share on Reddit">R</a>' +
        '<a class="share-btn" href="https://news.ycombinator.com/submitlink?u=' + url + '&t=' + text + '" target="_blank" rel="noopener" title="Share on Hacker News">Y</a>' +
        '<button class="share-btn share-copy" onclick="navigator.clipboard.writeText(window.location.href).then(function(){this.textContent=\'✓\';var b=this;setTimeout(function(){b.textContent=\'🔗\'},1500)}.bind(this))" title="Copy link">🔗</button>' +
        '</div>';
      meta.insertAdjacentHTML('afterend', shareHtml);
    }
  }

  // --- Prev/Next navigation ---
  if (currentIdx === -1) return;

  var newer = currentIdx > 0 ? articles[currentIdx - 1] : null;
  var older = currentIdx < articles.length - 1 ? articles[currentIdx + 1] : null;

  var navHtml = '<nav class="article-nav">';
  if (older) {
    navHtml += '<a href="' + older.slug + '.html" class="nav-link nav-older">' +
      '<span class="nav-dir">← Older</span>' +
      '<span class="nav-title">' + older.title + '</span></a>';
  } else {
    navHtml += '<span class="nav-link nav-placeholder"></span>';
  }
  if (newer) {
    navHtml += '<a href="' + newer.slug + '.html" class="nav-link nav-newer">' +
      '<span class="nav-dir">Newer →</span>' +
      '<span class="nav-title">' + newer.title + '</span></a>';
  } else {
    navHtml += '<span class="nav-link nav-placeholder"></span>';
  }
  navHtml += '</nav>';

  // Insert before the closing </article> or at the end of the story page
  var article = document.querySelector('.story-page');
  if (article) {
    article.insertAdjacentHTML('beforeend', navHtml);
  }
})();
