// Generated by the spaces CLI. Do not edit by hand.

import { executeAction, executeActionStream } from "@hatch/sdk";

export type DeletePersonRequest = {
  person_id: number;
};

export type DeletePersonResponse = {
  deleted_name: string;
  deleted_person_id: number;
  unlinked_faces: number;
};

export type GetPeopleRequest = Record<string, unknown>;

export type GetPeopleResponse = {
  people: Array<{
  face_count: number;
  id: number;
  name: string;
  thumbnail_base64: string;
}>;
  total: number;
};

export type GetPhotoDetailRequest = {
  photo_id: number;
};

export type GetPhotoDetailResponse = {
  faces: Array<{
  bbox_h: number;
  bbox_w: number;
  bbox_x: number;
  bbox_y: number;
  confidence: number;
  crop_base64: string;
  face_id: number;
  person_id: number | null;
  person_name: string | null;
}>;
  filename: string;
  height: number;
  num_faces: number;
  photo_base64: string;
  photo_id: number;
  upload_date: string;
  width: number;
};

export type GetPhotosRequest = {
  limit?: number;
  offset?: number;
  person_id?: number | null;
};

export type GetPhotosResponse = {
  photos: Array<{
  filename: string;
  height: number;
  id: number;
  num_faces: number;
  people_names: Array<string>;
  thumbnail_base64: string;
  upload_date: string;
  width: number;
}>;
  total: number;
};

export type MergePeopleRequest = {
  keep_person_id: number;
  merge_person_id: number;
};

export type MergePeopleResponse = {
  faces_moved: number;
  kept_name: string;
  kept_person_id: number;
  merged_name: string;
  merged_person_id: number;
  new_face_count: number;
};

export type RecognizeFacesRequest = {
  image_base64: string;
};

export type RecognizeFacesResponse = {
  faces: Array<{
  bbox_h: number;
  bbox_w: number;
  bbox_x: number;
  bbox_y: number;
  best_match_name: string | null;
  crop_base64: string;
  matches: Array<{
  confidence: number;
  distance: number;
  name: string;
  person_id: number;
}>;
}>;
  num_faces: number;
  photo_base64: string;
};

export type TagFaceRequest = {
  face_id: number;
  name: string;
};

export type TagFaceResponse = {
  face_id: number;
  is_new_person: boolean;
  person_id: number;
  person_name: string;
};

export type UploadPhotoRequest = {
  image_base64: string;
};

export type UploadPhotoResponse = {
  faces: Array<{
  bbox_h: number;
  bbox_w: number;
  bbox_x: number;
  bbox_y: number;
  confidence: number;
  crop_base64: string;
  face_id: number;
  matches: Array<Record<string, unknown>>;
}>;
  filename: string;
  height: number;
  num_faces: number;
  photo_base64: string;
  photo_id: number;
  width: number;
};

export class Space {
  static deletePerson(request: DeletePersonRequest): Promise<DeletePersonResponse> {
    return executeAction<DeletePersonResponse>("delete_person", request);
  }

  static deletePersonStream(request: DeletePersonRequest): AsyncIterable<DeletePersonResponse> {
    return executeActionStream<DeletePersonResponse>("delete_person", request);
  }

  static getPeople(request: GetPeopleRequest): Promise<GetPeopleResponse> {
    return executeAction<GetPeopleResponse>("get_people", request);
  }

  static getPeopleStream(request: GetPeopleRequest): AsyncIterable<GetPeopleResponse> {
    return executeActionStream<GetPeopleResponse>("get_people", request);
  }

  static getPhotoDetail(request: GetPhotoDetailRequest): Promise<GetPhotoDetailResponse> {
    return executeAction<GetPhotoDetailResponse>("get_photo_detail", request);
  }

  static getPhotoDetailStream(request: GetPhotoDetailRequest): AsyncIterable<GetPhotoDetailResponse> {
    return executeActionStream<GetPhotoDetailResponse>("get_photo_detail", request);
  }

  static getPhotos(request: GetPhotosRequest): Promise<GetPhotosResponse> {
    return executeAction<GetPhotosResponse>("get_photos", request);
  }

  static getPhotosStream(request: GetPhotosRequest): AsyncIterable<GetPhotosResponse> {
    return executeActionStream<GetPhotosResponse>("get_photos", request);
  }

  static mergePeople(request: MergePeopleRequest): Promise<MergePeopleResponse> {
    return executeAction<MergePeopleResponse>("merge_people", request);
  }

  static mergePeopleStream(request: MergePeopleRequest): AsyncIterable<MergePeopleResponse> {
    return executeActionStream<MergePeopleResponse>("merge_people", request);
  }

  static recognizeFaces(request: RecognizeFacesRequest): Promise<RecognizeFacesResponse> {
    return executeAction<RecognizeFacesResponse>("recognize_faces", request);
  }

  static recognizeFacesStream(request: RecognizeFacesRequest): AsyncIterable<RecognizeFacesResponse> {
    return executeActionStream<RecognizeFacesResponse>("recognize_faces", request);
  }

  static tagFace(request: TagFaceRequest): Promise<TagFaceResponse> {
    return executeAction<TagFaceResponse>("tag_face", request);
  }

  static tagFaceStream(request: TagFaceRequest): AsyncIterable<TagFaceResponse> {
    return executeActionStream<TagFaceResponse>("tag_face", request);
  }

  static uploadPhoto(request: UploadPhotoRequest): Promise<UploadPhotoResponse> {
    return executeAction<UploadPhotoResponse>("upload_photo", request);
  }

  static uploadPhotoStream(request: UploadPhotoRequest): AsyncIterable<UploadPhotoResponse> {
    return executeActionStream<UploadPhotoResponse>("upload_photo", request);
  }

}
