// Generated by the spaces CLI. Do not edit by hand.

import { executeAction, executeActionStream } from "@hatch/sdk";

export type ClickRequest = {
  viewport_height?: number;
  viewport_width?: number;
  x: number;
  y: number;
};

export type ClickResponse = {
  error?: string;
  ok: boolean;
};

export type EnsureBrowserRequest = {
  with_proxy?: boolean;
};

export type EnsureBrowserResponse = {
  chrome_running?: boolean;
  error?: string;
  ip?: string;
  ok: boolean;
  proxy_running?: boolean;
};

export type ExtractCookiesRequest = {
  domain?: string;
};

export type ExtractCookiesResponse = {
  cookie_count?: number;
  domains?: Array<string>;
  error?: string;
  ok: boolean;
};

export type GetInfoRequest = Record<string, unknown>;

export type GetInfoResponse = {
  error?: string;
  ok: boolean;
  title?: string;
  url?: string;
};

export type NavigateRequest = {
  url: string;
};

export type NavigateResponse = {
  error?: string;
  ok: boolean;
  title?: string;
  url?: string;
};

export type PressKeyRequest = {
  key: string;
};

export type PressKeyResponse = {
  error?: string;
  ok: boolean;
};

export type ScreenshotRequest = Record<string, unknown>;

export type ScreenshotResponse = {
  error?: string;
  image_url?: string;
  ok: boolean;
  timestamp?: number;
  title?: string;
  url?: string;
};

export type ScrollRequest = {
  amount?: number;
  direction?: string;
};

export type ScrollResponse = {
  error?: string;
  ok: boolean;
};

export type TypeTextRequest = {
  clear_first?: boolean;
  text: string;
  use_react_trick?: boolean;
};

export type TypeTextResponse = {
  error?: string;
  ok: boolean;
};

export class Space {
  static click(request: ClickRequest): Promise<ClickResponse> {
    return executeAction<ClickResponse>("click", request);
  }

  static clickStream(request: ClickRequest): AsyncIterable<ClickResponse> {
    return executeActionStream<ClickResponse>("click", request);
  }

  static ensureBrowser(request: EnsureBrowserRequest): Promise<EnsureBrowserResponse> {
    return executeAction<EnsureBrowserResponse>("ensure_browser", request);
  }

  static ensureBrowserStream(request: EnsureBrowserRequest): AsyncIterable<EnsureBrowserResponse> {
    return executeActionStream<EnsureBrowserResponse>("ensure_browser", request);
  }

  static extractCookies(request: ExtractCookiesRequest): Promise<ExtractCookiesResponse> {
    return executeAction<ExtractCookiesResponse>("extract_cookies", request);
  }

  static extractCookiesStream(request: ExtractCookiesRequest): AsyncIterable<ExtractCookiesResponse> {
    return executeActionStream<ExtractCookiesResponse>("extract_cookies", request);
  }

  static getInfo(request: GetInfoRequest): Promise<GetInfoResponse> {
    return executeAction<GetInfoResponse>("get_info", request);
  }

  static getInfoStream(request: GetInfoRequest): AsyncIterable<GetInfoResponse> {
    return executeActionStream<GetInfoResponse>("get_info", request);
  }

  static navigate(request: NavigateRequest): Promise<NavigateResponse> {
    return executeAction<NavigateResponse>("navigate", request);
  }

  static navigateStream(request: NavigateRequest): AsyncIterable<NavigateResponse> {
    return executeActionStream<NavigateResponse>("navigate", request);
  }

  static pressKey(request: PressKeyRequest): Promise<PressKeyResponse> {
    return executeAction<PressKeyResponse>("press_key", request);
  }

  static pressKeyStream(request: PressKeyRequest): AsyncIterable<PressKeyResponse> {
    return executeActionStream<PressKeyResponse>("press_key", request);
  }

  static screenshot(request: ScreenshotRequest): Promise<ScreenshotResponse> {
    return executeAction<ScreenshotResponse>("screenshot", request);
  }

  static screenshotStream(request: ScreenshotRequest): AsyncIterable<ScreenshotResponse> {
    return executeActionStream<ScreenshotResponse>("screenshot", request);
  }

  static scroll(request: ScrollRequest): Promise<ScrollResponse> {
    return executeAction<ScrollResponse>("scroll", request);
  }

  static scrollStream(request: ScrollRequest): AsyncIterable<ScrollResponse> {
    return executeActionStream<ScrollResponse>("scroll", request);
  }

  static typeText(request: TypeTextRequest): Promise<TypeTextResponse> {
    return executeAction<TypeTextResponse>("type_text", request);
  }

  static typeTextStream(request: TypeTextRequest): AsyncIterable<TypeTextResponse> {
    return executeActionStream<TypeTextResponse>("type_text", request);
  }

}
