// Generated by the spaces CLI. Do not edit by hand.

import { executeAction, executeActionStream } from "@hatch/sdk";

export type ClickRequest = {
  x: number;
  y: number;
};

export type ClickResponse = {
  error?: string;
  ok: boolean;
};

export type NavigateRequest = {
  url: string;
};

export type NavigateResponse = {
  error?: string;
  ok: boolean;
  title?: string;
  url?: string;
};

export type PressKeyRequest = {
  key: string;
};

export type PressKeyResponse = {
  error?: string;
  ok: boolean;
};

export type ScreenshotRequest = {
  quality?: number;
};

export type ScreenshotResponse = {
  error?: string;
  image_base64?: string;
  ok: boolean;
  title?: string;
  url?: string;
};

export type ScrollRequest = {
  amount?: number;
  direction?: string;
};

export type ScrollResponse = {
  error?: string;
  ok: boolean;
};

export type TypeTextRequest = {
  clear_first?: boolean;
  text: string;
};

export type TypeTextResponse = {
  error?: string;
  ok: boolean;
};

export class Space {
  static click(request: ClickRequest): Promise<ClickResponse> {
    return executeAction<ClickResponse>("click", request);
  }

  static clickStream(request: ClickRequest): AsyncIterable<ClickResponse> {
    return executeActionStream<ClickResponse>("click", request);
  }

  static navigate(request: NavigateRequest): Promise<NavigateResponse> {
    return executeAction<NavigateResponse>("navigate", request);
  }

  static navigateStream(request: NavigateRequest): AsyncIterable<NavigateResponse> {
    return executeActionStream<NavigateResponse>("navigate", request);
  }

  static pressKey(request: PressKeyRequest): Promise<PressKeyResponse> {
    return executeAction<PressKeyResponse>("press_key", request);
  }

  static pressKeyStream(request: PressKeyRequest): AsyncIterable<PressKeyResponse> {
    return executeActionStream<PressKeyResponse>("press_key", request);
  }

  static screenshot(request: ScreenshotRequest): Promise<ScreenshotResponse> {
    return executeAction<ScreenshotResponse>("screenshot", request);
  }

  static screenshotStream(request: ScreenshotRequest): AsyncIterable<ScreenshotResponse> {
    return executeActionStream<ScreenshotResponse>("screenshot", request);
  }

  static scroll(request: ScrollRequest): Promise<ScrollResponse> {
    return executeAction<ScrollResponse>("scroll", request);
  }

  static scrollStream(request: ScrollRequest): AsyncIterable<ScrollResponse> {
    return executeActionStream<ScrollResponse>("scroll", request);
  }

  static typeText(request: TypeTextRequest): Promise<TypeTextResponse> {
    return executeAction<TypeTextResponse>("type_text", request);
  }

  static typeTextStream(request: TypeTextRequest): AsyncIterable<TypeTextResponse> {
    return executeActionStream<TypeTextResponse>("type_text", request);
  }

}
