// Generated by the spaces CLI. Do not edit by hand.

import { executeAction, executeActionStream } from "@hatch/sdk";

export type GetSystemMetricsRequest = {
  dummy?: string;
};

export type GetSystemMetricsResponse = {
  dummy: string;
};

export class Space {
  static getSystemMetrics(request: GetSystemMetricsRequest): Promise<GetSystemMetricsResponse> {
    return executeAction<GetSystemMetricsResponse>("get_system_metrics", request);
  }

  static getSystemMetricsStream(request: GetSystemMetricsRequest): AsyncIterable<GetSystemMetricsResponse> {
    return executeActionStream<GetSystemMetricsResponse>("get_system_metrics", request);
  }

}
