// Generated by the spaces CLI. Do not edit by hand.

import { executeAction, executeActionStream } from "@hatch/sdk";

export type GetAnalyticsRequest = Record<string, unknown>;

export type GetAnalyticsResponse = {
  avg_price: number | null;
  brands: Array<{
  avg_price: number | null;
  brand: string;
  count: number;
  max_price: number | null;
  median_price: number | null;
  min_price: number | null;
}>;
  groups: Array<{
  active: number;
  avg_price: number | null;
  count: number;
  group_name: string;
  sold: number;
}>;
  last_sync: string;
  median_price: number | null;
  scatter: Array<{
  brand: string;
  date: string;
  model: string;
  price: number;
  reference: string;
}>;
  timeline: Array<{
  avg_price: number | null;
  count: number;
  date: string;
}>;
  total_active: number;
  total_listings: number;
  total_sold: number;
  total_with_price: number;
};

export type GetListingsRequest = {
  brand?: string;
  group?: string;
  limit?: number;
  max_price?: number | null;
  min_price?: number | null;
  offset?: number;
  search?: string;
  sold_filter?: string;
  sort_by?: string;
};

export type GetListingsResponse = {
  has_more: boolean;
  listings: Array<{
  brand: string;
  condition: string | null;
  contents: string | null;
  date: string;
  group_name: string;
  id: string;
  location: string | null;
  model: string;
  original_price: number | null;
  post_url: string;
  price: number | null;
  reference: string;
  scraped_at: string;
  seller: string;
  sold: boolean;
}>;
  total: number;
};

export type GetWatchlistRequest = Record<string, unknown>;

export type GetWatchlistResponse = {
  targets: Array<{
  avg_price: number | null;
  highest_price: number | null;
  last_seen: string | null;
  lowest_price: number | null;
  matches: Array<{
  condition: string | null;
  contents: string | null;
  date: string;
  group_name: string;
  listing_id: string;
  post_url: string;
  price: number | null;
  raw_text: string;
  seller: string;
  sold: boolean;
}>;
  name: string;
  note: string;
  ref: string;
}>;
};

export class Space {
  static getAnalytics(request: GetAnalyticsRequest): Promise<GetAnalyticsResponse> {
    return executeAction<GetAnalyticsResponse>("get_analytics", request);
  }

  static getAnalyticsStream(request: GetAnalyticsRequest): AsyncIterable<GetAnalyticsResponse> {
    return executeActionStream<GetAnalyticsResponse>("get_analytics", request);
  }

  static getListings(request: GetListingsRequest): Promise<GetListingsResponse> {
    return executeAction<GetListingsResponse>("get_listings", request);
  }

  static getListingsStream(request: GetListingsRequest): AsyncIterable<GetListingsResponse> {
    return executeActionStream<GetListingsResponse>("get_listings", request);
  }

  static getWatchlist(request: GetWatchlistRequest): Promise<GetWatchlistResponse> {
    return executeAction<GetWatchlistResponse>("get_watchlist", request);
  }

  static getWatchlistStream(request: GetWatchlistRequest): AsyncIterable<GetWatchlistResponse> {
    return executeActionStream<GetWatchlistResponse>("get_watchlist", request);
  }

}
